const screenshotTest = require('../../screenshotTest-async.js');
const setup = {
  'accordion': [
    'default',
    'accordion-with-custom-icons',
    'no-bounding-box-accordion',
    'custom-css-properties',
    'title-with-different-icon-sizes',
  ],
  'accordionbody': ['default'],
  'accordiontitle': ['default'],
  'avatar': [
    'default',
    'size-variants',
    'light-and-dark-mode-variants',
    'shape-variants',
  ],
  'buttongroup': ['default'],
  'button': [
    'primary',
    'secondary',
    'danger',
    'link',
    'text',
    'block',
    'small',
    'mini',
    'icon',
    'icon-text',
    'caret-with-icon',
  ],
  'checkbox': [
    'default',
    'checked',
    'disabled',
    'checked-disabled',
    'with-label',
    'disabled-with-label',
    'with-description-and-label',
    'with-description-and-label-disabled',
  ],
  'datepicker': [
    'default',
    'datepicker-open',
    'datepicker-month-open',
    'datepicker-year-open',
    'date-picker-range',
    'date-picker-range-open',
    'min-date-and-max-date-specified',
    'date-format-and-placeholder-specified',
  ],
  'datatable': [
    'default',
    'selectable',
    'sticky-header',
    'user-column-variant',
    'icon-column-variant',
    'paragraph-column-variant',
    'column-text-alignment',
    'row-actions',
    'hide-column',
  ],
  'formatdate': ['custom-date'],
  'fileuploader': ['default', 'multifile'],
  'form': ['default'],
  'formcontrol': ['default'],
  'formatnumber': ['default', 'currency'],
  'icons': ['default'],
  'inline-message': ['default', 'info', 'success', 'error', 'warning'],
};
const DELAY = 0;
screenshotTest(setup, DELAY);
