/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface FwButton1 {
        /**
          * Identifier of  the theme based on which the button is styled.
         */
        "color": 'primary' | 'secondary' | 'danger' | 'link' | 'text';
        /**
          * Disables the button on the interface. If the attribute’s value is undefined, the value is set to false.
         */
        "disabled": boolean;
        /**
          * Sets the button to a full-width block. If the attribute’s value is undefined, the value is set to false.
         */
        "expand": boolean;
        /**
          * Accepts the id of the fw-modal component to open it on click
         */
        "modalTriggerId": string;
        /**
          * Size of the button.
         */
        "size": 'normal' | 'mini' | 'small';
        /**
          * Button type based on which actions are performed when the button is clicked.
         */
        "type": 'button' | 'reset' | 'submit';
    }
}
declare global {
    interface HTMLFwButton1Element extends Components.FwButton1, HTMLStencilElement {
    }
    var HTMLFwButton1Element: {
        prototype: HTMLFwButton1Element;
        new (): HTMLFwButton1Element;
    };
    interface HTMLElementTagNameMap {
        "fw-button1": HTMLFwButton1Element;
    }
}
declare namespace LocalJSX {
    interface FwButton1 {
        /**
          * Identifier of  the theme based on which the button is styled.
         */
        "color"?: 'primary' | 'secondary' | 'danger' | 'link' | 'text';
        /**
          * Disables the button on the interface. If the attribute’s value is undefined, the value is set to false.
         */
        "disabled"?: boolean;
        /**
          * Sets the button to a full-width block. If the attribute’s value is undefined, the value is set to false.
         */
        "expand"?: boolean;
        /**
          * Accepts the id of the fw-modal component to open it on click
         */
        "modalTriggerId"?: string;
        /**
          * Triggered when the button loses focus.
         */
        "onFwBlur"?: (event: CustomEvent<void>) => void;
        /**
          * Triggered when the button is clicked.
         */
        "onFwClick"?: (event: CustomEvent<void>) => void;
        /**
          * Triggered when the button comes into focus.
         */
        "onFwFocus"?: (event: CustomEvent<void>) => void;
        /**
          * Size of the button.
         */
        "size"?: 'normal' | 'mini' | 'small';
        /**
          * Button type based on which actions are performed when the button is clicked.
         */
        "type"?: 'button' | 'reset' | 'submit';
    }
    interface IntrinsicElements {
        "fw-button1": FwButton1;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "fw-button1": LocalJSX.FwButton1 & JSXBase.HTMLAttributes<HTMLFwButton1Element>;
        }
    }
}
