module.exports = () => {
  return JSON.stringify({
    plugins: [
      { removeDoctype: false },
      { removeXMLProcInst: false },
      { removeComments: false },
      { removeMetadata: false },
      { removeXMLNS: true },
      { removeEditorsNSData: false },
      { cleanupAttrs: false },
      { inlineStyles: false },
      { minifyStyles: false },
      { convertStyleToAttrs: false },
      { cleanupIDs: false },
      { prefixIds: false },
      { removeRasterImages: false },
      { removeUselessDefs: false },
      { cleanupNumericValues: false },
      { cleanupListOfValues: false },
      { convertColors: false },
      { removeUnknownsAndDefaults: false },
      { removeNonInheritableGroupAttrs: false },
      { removeUselessStrokeAndFill: false },
      { removeViewBox: false },
      { cleanupEnableBackground: false },
      { removeHiddenElems: false },
      { removeEmptyText: false },
      { convertShapeToPath: false },
      { convertEllipseToCircle: false },
      { moveElemsAttrsToGroup: false },
      { moveGroupAttrsToElems: false },
      { collapseGroups: false },
      { convertPathData: { noSpaceAfterFlags: false } },
      { convertTransform: false },
      { removeEmptyAttrs: false },
      { removeEmptyContainers: false },
      { mergePaths: { noSpaceAfterFlags: false } },
      { removeUnusedNS: false },
      { sortAttrs: false },
      { sortDefsChildren: false },
      { removeTitle: false },
      { removeDesc: false },
      { removeDimensions: true },
      { removeAttrs: false },
      { removeAttributesBySelector: false },
      { removeElementsByAttr: false },
      { addClassesToSVGElement: false },
      { removeStyleElement: true },
      { removeScriptElement: true },
      { addAttributesToSVGElement: false },
      { removeOffCanvasPaths: false },
      { reusePaths: false },
    ],
  });
};
