export default [
  {
    country_name: 'Afghanistan',
    native: 'افغانستان',
    phone: '93',
    continent_name: 'AS',
    capital: 'Kabul',
    currency: 'AFN',
    languages: ['ps', 'uz', 'tk'],
    emoji: '🇦🇫',
    emojiU: 'U+1F1E6 U+1F1EB',
    code3l: 'AFG',
    code2l: 'AF',
  },
  {
    country_name: 'Albania',
    native: 'Shqipëria',
    phone: '355',
    continent_name: 'EU',
    capital: 'Tirana',
    currency: 'ALL',
    languages: ['sq'],
    emoji: '🇦🇱',
    emojiU: 'U+1F1E6 U+1F1F1',
    code3l: 'ALB',
    code2l: 'AL',
  },
  {
    country_name: 'Algeria',
    native: 'الجزائر',
    phone: '213',
    continent_name: 'AF',
    capital: 'Algiers',
    currency: 'DZD',
    languages: ['ar'],
    emoji: '🇩🇿',
    emojiU: 'U+1F1E9 U+1F1FF',
    code3l: 'DZA',
    code2l: 'DZ',
  },
  {
    country_name: 'American Samoa',
    native: 'American Samoa',
    phone: '1',
    continent_name: 'OC',
    capital: 'Pago Pago',
    currency: 'USD',
    languages: ['en', 'sm'],
    emoji: '🇦🇸',
    emojiU: 'U+1F1E6 U+1F1F8',
    code3l: 'ASM',
    code2l: 'AS',
  },
  {
    country_name: 'Andorra',
    native: 'Andorra',
    phone: '376',
    continent_name: 'EU',
    capital: 'Andorra la Vella',
    currency: 'EUR',
    languages: ['ca'],
    emoji: '🇦🇩',
    emojiU: 'U+1F1E6 U+1F1E9',
    code3l: 'AND',
    code2l: 'AD',
  },
  {
    country_name: 'Angola',
    native: 'Angola',
    phone: '244',
    continent_name: 'AF',
    capital: 'Luanda',
    currency: 'AOA',
    languages: ['pt'],
    emoji: '🇦🇴',
    emojiU: 'U+1F1E6 U+1F1F4',
    code3l: 'AGO',
    code2l: 'AO',
  },
  {
    country_name: 'Anguilla',
    native: 'Anguilla',
    phone: '1',
    continent_name: 'NA',
    capital: 'The Valley',
    currency: 'XCD',
    languages: ['en'],
    emoji: '🇦🇮',
    emojiU: 'U+1F1E6 U+1F1EE',
    code3l: 'AIA',
    code2l: 'AI',
  },
  {
    country_name: 'Antarctica',
    native: 'Antarctica',
    phone: '672',
    continent_name: 'AN',
    capital: '',
    currency: '',
    languages: [],
    emoji: '🇦🇶',
    emojiU: 'U+1F1E6 U+1F1F6',
    code3l: 'ATA',
    code2l: 'AQ',
  },
  {
    country_name: 'Antigua and Barbuda',
    native: 'Antigua and Barbuda',
    phone: '1',
    continent_name: 'NA',
    capital: "Saint John's",
    currency: 'XCD',
    languages: ['en'],
    emoji: '🇦🇬',
    emojiU: 'U+1F1E6 U+1F1EC',
    code3l: 'ATG',
    code2l: 'AG',
  },
  {
    country_name: 'Argentina',
    native: 'Argentina',
    phone: '54',
    continent_name: 'SA',
    capital: 'Buenos Aires',
    currency: 'ARS',
    languages: ['es', 'gn'],
    emoji: '🇦🇷',
    emojiU: 'U+1F1E6 U+1F1F7',
    code3l: 'ARG',
    code2l: 'AR',
  },
  {
    country_name: 'Armenia',
    native: 'Հայաստան',
    phone: '374',
    continent_name: 'AS',
    capital: 'Yerevan',
    currency: 'AMD',
    languages: ['hy', 'ru'],
    emoji: '🇦🇲',
    emojiU: 'U+1F1E6 U+1F1F2',
    code3l: 'ARM',
    code2l: 'AM',
  },
  {
    country_name: 'Aruba',
    native: 'Aruba',
    phone: '297',
    continent_name: 'NA',
    capital: 'Oranjestad',
    currency: 'AWG',
    languages: ['nl', 'pa'],
    emoji: '🇦🇼',
    emojiU: 'U+1F1E6 U+1F1FC',
    code3l: 'ABW',
    code2l: 'AW',
  },
  {
    country_name: 'Australia',
    native: 'Australia',
    phone: '61',
    continent_name: 'OC',
    capital: 'Canberra',
    currency: 'AUD',
    languages: ['en'],
    emoji: '🇦🇺',
    emojiU: 'U+1F1E6 U+1F1FA',
    code3l: 'AUS',
    code2l: 'AU',
  },
  {
    country_name: 'Austria',
    native: 'Österreich',
    phone: '43',
    continent_name: 'EU',
    capital: 'Vienna',
    currency: 'EUR',
    languages: ['de'],
    emoji: '🇦🇹',
    emojiU: 'U+1F1E6 U+1F1F9',
    code3l: 'AUT',
    code2l: 'AT',
  },
  {
    country_name: 'Azerbaijan',
    native: 'Azərbaycan',
    phone: '994',
    continent_name: 'AS',
    capital: 'Baku',
    currency: 'AZN',
    languages: ['az'],
    emoji: '🇦🇿',
    emojiU: 'U+1F1E6 U+1F1FF',
    code3l: 'AZE',
    code2l: 'AZ',
  },
  {
    country_name: 'Bahamas',
    native: 'Bahamas',
    phone: '1',
    continent_name: 'NA',
    capital: 'Nassau',
    currency: 'BSD',
    languages: ['en'],
    emoji: '🇧🇸',
    emojiU: 'U+1F1E7 U+1F1F8',
    code3l: 'BHS',
    code2l: 'BS',
  },
  {
    country_name: 'Bahrain',
    native: '‏البحرين',
    phone: '973',
    continent_name: 'AS',
    capital: 'Manama',
    currency: 'BHD',
    languages: ['ar'],
    emoji: '🇧🇭',
    emojiU: 'U+1F1E7 U+1F1ED',
    code3l: 'BHR',
    code2l: 'BH',
  },
  {
    country_name: 'Bangladesh',
    native: 'Bangladesh',
    phone: '880',
    continent_name: 'AS',
    capital: 'Dhaka',
    currency: 'BDT',
    languages: ['bn'],
    emoji: '🇧🇩',
    emojiU: 'U+1F1E7 U+1F1E9',
    code3l: 'BGD',
    code2l: 'BD',
  },
  {
    country_name: 'Barbados',
    native: 'Barbados',
    phone: '1',
    continent_name: 'NA',
    capital: 'Bridgetown',
    currency: 'BBD',
    languages: ['en'],
    emoji: '🇧🇧',
    emojiU: 'U+1F1E7 U+1F1E7',
    code3l: 'BRB',
    code2l: 'BB',
  },
  {
    country_name: 'Belarus',
    native: 'Белару́сь',
    phone: '375',
    continent_name: 'EU',
    capital: 'Minsk',
    currency: 'BYN',
    languages: ['be', 'ru'],
    emoji: '🇧🇾',
    emojiU: 'U+1F1E7 U+1F1FE',
    code3l: 'BLR',
    code2l: 'BY',
  },
  {
    country_name: 'Belgium',
    native: 'België',
    phone: '32',
    continent_name: 'EU',
    capital: 'Brussels',
    currency: 'EUR',
    languages: ['nl', 'fr', 'de'],
    emoji: '🇧🇪',
    emojiU: 'U+1F1E7 U+1F1EA',
    code3l: 'BEL',
    code2l: 'BE',
  },
  {
    country_name: 'Belize',
    native: 'Belize',
    phone: '501',
    continent_name: 'NA',
    capital: 'Belmopan',
    currency: 'BZD',
    languages: ['en', 'es'],
    emoji: '🇧🇿',
    emojiU: 'U+1F1E7 U+1F1FF',
    code3l: 'BLZ',
    code2l: 'BZ',
  },
  {
    country_name: 'Benin',
    native: 'Bénin',
    phone: '229',
    continent_name: 'AF',
    capital: 'Porto-Novo',
    currency: 'XOF',
    languages: ['fr'],
    emoji: '🇧🇯',
    emojiU: 'U+1F1E7 U+1F1EF',
    code3l: 'BEN',
    code2l: 'BJ',
  },
  {
    country_name: 'Bermuda',
    native: 'Bermuda',
    phone: '1',
    continent_name: 'NA',
    capital: 'Hamilton',
    currency: 'BMD',
    languages: ['en'],
    emoji: '🇧🇲',
    emojiU: 'U+1F1E7 U+1F1F2',
    code3l: 'BMU',
    code2l: 'BM',
  },
  {
    country_name: 'Bhutan',
    native: 'ʼbrug-yul',
    phone: '975',
    continent_name: 'AS',
    capital: 'Thimphu',
    currency: 'BTN,INR',
    languages: ['dz'],
    emoji: '🇧🇹',
    emojiU: 'U+1F1E7 U+1F1F9',
    code3l: 'BTN',
    code2l: 'BT',
  },
  {
    country_name: 'Bosnia and Herzegovina',
    native: 'Bosna i Hercegovina',
    phone: '387',
    continent_name: 'EU',
    capital: 'Sarajevo',
    currency: 'BAM',
    languages: ['bs', 'hr', 'sr'],
    emoji: '🇧🇦',
    emojiU: 'U+1F1E7 U+1F1E6',
    code3l: 'BIH',
    code2l: 'BA',
  },
  {
    country_name: 'Botswana',
    native: 'Botswana',
    phone: '267',
    continent_name: 'AF',
    capital: 'Gaborone',
    currency: 'BWP',
    languages: ['en', 'tn'],
    emoji: '🇧🇼',
    emojiU: 'U+1F1E7 U+1F1FC',
    code3l: 'BWA',
    code2l: 'BW',
  },
  {
    country_name: 'Bouvet Island',
    native: 'Bouvetøya',
    phone: '47',
    continent_name: 'AN',
    capital: '',
    currency: 'NOK',
    languages: ['no', 'nb', 'nn'],
    emoji: '🇧🇻',
    emojiU: 'U+1F1E7 U+1F1FB',
    code3l: 'BVT',
    code2l: 'BV',
  },
  {
    country_name: 'Brazil',
    native: 'Brasil',
    phone: '55',
    continent_name: 'SA',
    capital: 'Brasília',
    currency: 'BRL',
    languages: ['pt'],
    emoji: '🇧🇷',
    emojiU: 'U+1F1E7 U+1F1F7',
    code3l: 'BRA',
    code2l: 'BR',
  },
  {
    country_name: 'Bulgaria',
    native: 'България',
    phone: '359',
    continent_name: 'EU',
    capital: 'Sofia',
    currency: 'BGN',
    languages: ['bg'],
    emoji: '🇧🇬',
    emojiU: 'U+1F1E7 U+1F1EC',
    code3l: 'BGR',
    code2l: 'BG',
  },
  {
    country_name: 'Burkina Faso',
    native: 'Burkina Faso',
    phone: '226',
    continent_name: 'AF',
    capital: 'Ouagadougou',
    currency: 'XOF',
    languages: ['fr', 'ff'],
    emoji: '🇧🇫',
    emojiU: 'U+1F1E7 U+1F1EB',
    code3l: 'BFA',
    code2l: 'BF',
  },
  {
    country_name: 'Burundi',
    native: 'Burundi',
    phone: '257',
    continent_name: 'AF',
    capital: 'Bujumbura',
    currency: 'BIF',
    languages: ['fr', 'rn'],
    emoji: '🇧🇮',
    emojiU: 'U+1F1E7 U+1F1EE',
    code3l: 'BDI',
    code2l: 'BI',
  },
  {
    country_name: 'Cape Verde',
    native: 'Cabo Verde',
    phone: '238',
    continent_name: 'AF',
    capital: 'Praia',
    currency: 'CVE',
    languages: ['pt'],
    emoji: '🇨🇻',
    emojiU: 'U+1F1E8 U+1F1FB',
    code3l: 'CPV',
    code2l: 'CV',
  },
  {
    country_name: 'Cambodia',
    native: 'Kâmpŭchéa',
    phone: '855',
    continent_name: 'AS',
    capital: 'Phnom Penh',
    currency: 'KHR',
    languages: ['km'],
    emoji: '🇰🇭',
    emojiU: 'U+1F1F0 U+1F1ED',
    code3l: 'KHM',
    code2l: 'KH',
  },
  {
    country_name: 'Cameroon',
    native: 'Cameroon',
    phone: '237',
    continent_name: 'AF',
    capital: 'Yaoundé',
    currency: 'XAF',
    languages: ['en', 'fr'],
    emoji: '🇨🇲',
    emojiU: 'U+1F1E8 U+1F1F2',
    code3l: 'CMR',
    code2l: 'CM',
  },
  {
    country_name: 'Canada',
    native: 'Canada',
    phone: '1',
    continent_name: 'NA',
    capital: 'Ottawa',
    currency: 'CAD',
    languages: ['en', 'fr'],
    emoji: '🇨🇦',
    emojiU: 'U+1F1E8 U+1F1E6',
    code3l: 'CAN',
    code2l: 'CA',
  },
  {
    country_name: 'Cayman Islands',
    native: 'Cayman Islands',
    phone: '1',
    continent_name: 'NA',
    capital: 'George Town',
    currency: 'KYD',
    languages: ['en'],
    emoji: '🇰🇾',
    emojiU: 'U+1F1F0 U+1F1FE',
    code3l: 'CYM',
    code2l: 'KY',
  },
  {
    country_name: 'Central African Republic',
    native: 'Ködörösêse tî Bêafrîka',
    phone: '236',
    continent_name: 'AF',
    capital: 'Bangui',
    currency: 'XAF',
    languages: ['fr', 'sg'],
    emoji: '🇨🇫',
    emojiU: 'U+1F1E8 U+1F1EB',
    code3l: 'CAF',
    code2l: 'CF',
  },
  {
    country_name: 'Chad',
    native: 'Tchad',
    phone: '235',
    continent_name: 'AF',
    capital: "N'Djamena",
    currency: 'XAF',
    languages: ['fr', 'ar'],
    emoji: '🇹🇩',
    emojiU: 'U+1F1F9 U+1F1E9',
    code3l: 'TCD',
    code2l: 'TD',
  },
  {
    country_name: 'Chile',
    native: 'Chile',
    phone: '56',
    continent_name: 'SA',
    capital: 'Santiago',
    currency: 'CLF,CLP',
    languages: ['es'],
    emoji: '🇨🇱',
    emojiU: 'U+1F1E8 U+1F1F1',
    code3l: 'CHL',
    code2l: 'CL',
  },
  {
    country_name: 'China',
    native: '中国',
    phone: '86',
    continent_name: 'AS',
    capital: 'Beijing',
    currency: 'CNY',
    languages: ['zh'],
    emoji: '🇨🇳',
    emojiU: 'U+1F1E8 U+1F1F3',
    code3l: 'CHN',
    code2l: 'CN',
  },
  {
    country_name: 'Christmas Island',
    native: 'Christmas Island',
    phone: '61',
    continent_name: 'AS',
    capital: 'Flying Fish Cove',
    currency: 'AUD',
    languages: ['en'],
    emoji: '🇨🇽',
    emojiU: 'U+1F1E8 U+1F1FD',
    code3l: 'CXR',
    code2l: 'CX',
  },
  {
    country_name: 'Cocos [Keeling] Islands',
    native: 'Cocos (Keeling) Islands',
    phone: '61',
    continent_name: 'AS',
    capital: 'West Island',
    currency: 'AUD',
    languages: ['en'],
    emoji: '🇨🇨',
    emojiU: 'U+1F1E8 U+1F1E8',
    code3l: 'CCK',
    code2l: 'CC',
  },
  {
    country_name: 'Colombia',
    native: 'Colombia',
    phone: '57',
    continent_name: 'SA',
    capital: 'Bogotá',
    currency: 'COP',
    languages: ['es'],
    emoji: '🇨🇴',
    emojiU: 'U+1F1E8 U+1F1F4',
    code3l: 'COL',
    code2l: 'CO',
  },
  {
    country_name: 'Comoros',
    native: 'Komori',
    phone: '269',
    continent_name: 'AF',
    capital: 'Moroni',
    currency: 'KMF',
    languages: ['ar', 'fr'],
    emoji: '🇰🇲',
    emojiU: 'U+1F1F0 U+1F1F2',
    code3l: 'COM',
    code2l: 'KM',
  },
  {
    country_name: 'Cook Islands',
    native: 'Cook Islands',
    phone: '682',
    continent_name: 'OC',
    capital: 'Avarua',
    currency: 'NZD',
    languages: ['en'],
    emoji: '🇨🇰',
    emojiU: 'U+1F1E8 U+1F1F0',
    code3l: 'COK',
    code2l: 'CK',
  },
  {
    country_name: 'Costa Rica',
    native: 'Costa Rica',
    phone: '506',
    continent_name: 'NA',
    capital: 'San José',
    currency: 'CRC',
    languages: ['es'],
    emoji: '🇨🇷',
    emojiU: 'U+1F1E8 U+1F1F7',
    code3l: 'CRI',
    code2l: 'CR',
  },
  {
    country_name: 'Ivory Coast',
    native: "Côte d'Ivoire",
    phone: '225',
    continent_name: 'AF',
    capital: 'Yamoussoukro',
    currency: 'XOF',
    languages: ['fr'],
    emoji: '🇨🇮',
    emojiU: 'U+1F1E8 U+1F1EE',
    code3l: 'CIV',
    code2l: 'CI',
  },
  {
    country_name: 'Croatia',
    native: 'Hrvatska',
    phone: '385',
    continent_name: 'EU',
    capital: 'Zagreb',
    currency: 'HRK',
    languages: ['hr'],
    emoji: '🇭🇷',
    emojiU: 'U+1F1ED U+1F1F7',
    code3l: 'HRV',
    code2l: 'HR',
  },
  {
    country_name: 'Cuba',
    native: 'Cuba',
    phone: '53',
    continent_name: 'NA',
    capital: 'Havana',
    currency: 'CUC,CUP',
    languages: ['es'],
    emoji: '🇨🇺',
    emojiU: 'U+1F1E8 U+1F1FA',
    code3l: 'CUB',
    code2l: 'CU',
  },
  {
    country_name: 'Curacao',
    native: 'Curaçao',
    phone: '599',
    continent_name: 'NA',
    capital: 'Willemstad',
    currency: 'ANG',
    languages: ['nl', 'pa', 'en'],
    emoji: '🇨🇼',
    emojiU: 'U+1F1E8 U+1F1FC',
    code3l: 'CUW',
    code2l: 'CW',
  },
  {
    country_name: 'Cyprus',
    native: 'Κύπρος',
    phone: '357',
    continent_name: 'EU',
    capital: 'Nicosia',
    currency: 'EUR',
    languages: ['el', 'tr', 'hy'],
    emoji: '🇨🇾',
    emojiU: 'U+1F1E8 U+1F1FE',
    code3l: 'CYP',
    code2l: 'CY',
  },
  {
    country_name: 'Democratic Republic of the Congo',
    native: 'République démocratique du Congo',
    phone: '243',
    continent_name: 'AF',
    capital: 'Kinshasa',
    currency: 'CDF',
    languages: ['fr', 'ln', 'kg', 'sw', 'lu'],
    emoji: '🇨🇩',
    emojiU: 'U+1F1E8 U+1F1E9',
    code3l: 'COD',
    code2l: 'CD',
  },
  {
    country_name: 'Denmark',
    native: 'Danmark',
    phone: '45',
    continent_name: 'EU',
    capital: 'Copenhagen',
    currency: 'DKK',
    languages: ['da'],
    emoji: '🇩🇰',
    emojiU: 'U+1F1E9 U+1F1F0',
    code3l: 'DNK',
    code2l: 'DK',
  },
  {
    country_name: 'Djibouti',
    native: 'Djibouti',
    phone: '253',
    continent_name: 'AF',
    capital: 'Djibouti',
    currency: 'DJF',
    languages: ['fr', 'ar'],
    emoji: '🇩🇯',
    emojiU: 'U+1F1E9 U+1F1EF',
    code3l: 'DJI',
    code2l: 'DJ',
  },
  {
    country_name: 'Dominica',
    native: 'Dominica',
    phone: '1',
    continent_name: 'NA',
    capital: 'Roseau',
    currency: 'XCD',
    languages: ['en'],
    emoji: '🇩🇲',
    emojiU: 'U+1F1E9 U+1F1F2',
    code3l: 'DMA',
    code2l: 'DM',
  },
  {
    country_name: 'Ecuador',
    native: 'Ecuador',
    phone: '593',
    continent_name: 'SA',
    capital: 'Quito',
    currency: 'USD',
    languages: ['es'],
    emoji: '🇪🇨',
    emojiU: 'U+1F1EA U+1F1E8',
    code3l: 'ECU',
    code2l: 'EC',
  },
  {
    country_name: 'Egypt',
    native: 'مصر‎',
    phone: '20',
    continent_name: 'AF',
    capital: 'Cairo',
    currency: 'EGP',
    languages: ['ar'],
    emoji: '🇪🇬',
    emojiU: 'U+1F1EA U+1F1EC',
    code3l: 'EGY',
    code2l: 'EG',
  },
  {
    country_name: 'El Salvador',
    native: 'El Salvador',
    phone: '503',
    continent_name: 'NA',
    capital: 'San Salvador',
    currency: 'SVC,USD',
    languages: ['es'],
    emoji: '🇸🇻',
    emojiU: 'U+1F1F8 U+1F1FB',
    code3l: 'SLV',
    code2l: 'SV',
  },
  {
    country_name: 'Eritrea',
    native: 'ኤርትራ',
    phone: '291',
    continent_name: 'AF',
    capital: 'Asmara',
    currency: 'ERN',
    languages: ['ti', 'ar', 'en'],
    emoji: '🇪🇷',
    emojiU: 'U+1F1EA U+1F1F7',
    code3l: 'ERI',
    code2l: 'ER',
  },
  {
    country_name: 'Estonia',
    native: 'Eesti',
    phone: '372',
    continent_name: 'EU',
    capital: 'Tallinn',
    currency: 'EUR',
    languages: ['et'],
    emoji: '🇪🇪',
    emojiU: 'U+1F1EA U+1F1EA',
    code3l: 'EST',
    code2l: 'EE',
  },
  {
    country_name: 'Ethiopia',
    native: 'ኢትዮጵያ',
    phone: '251',
    continent_name: 'AF',
    capital: 'Addis Ababa',
    currency: 'ETB',
    languages: ['am'],
    emoji: '🇪🇹',
    emojiU: 'U+1F1EA U+1F1F9',
    code3l: 'ETH',
    code2l: 'ET',
  },
  {
    country_name: 'Fiji',
    native: 'Fiji',
    phone: '679',
    continent_name: 'OC',
    capital: 'Suva',
    currency: 'FJD',
    languages: ['en', 'fj', 'hi', 'ur'],
    emoji: '🇫🇯',
    emojiU: 'U+1F1EB U+1F1EF',
    code3l: 'FJI',
    code2l: 'FJ',
  },
  {
    country_name: 'Finland',
    native: 'Suomi',
    phone: '358',
    continent_name: 'EU',
    capital: 'Helsinki',
    currency: 'EUR',
    languages: ['fi', 'sv'],
    emoji: '🇫🇮',
    emojiU: 'U+1F1EB U+1F1EE',
    code3l: 'FIN',
    code2l: 'FI',
  },
  {
    country_name: 'France',
    native: 'France',
    phone: '33',
    continent_name: 'EU',
    capital: 'Paris',
    currency: 'EUR',
    languages: ['fr'],
    emoji: '🇫🇷',
    emojiU: 'U+1F1EB U+1F1F7',
    code3l: 'FRA',
    code2l: 'FR',
  },
  {
    country_name: 'French Guiana',
    native: 'Guyane française',
    phone: '594',
    continent_name: 'SA',
    capital: 'Cayenne',
    currency: 'EUR',
    languages: ['fr'],
    emoji: '🇬🇫',
    emojiU: 'U+1F1EC U+1F1EB',
    code3l: 'GUF',
    code2l: 'GF',
  },
  {
    country_name: 'French Polynesia',
    native: 'Polynésie française',
    phone: '689',
    continent_name: 'OC',
    capital: 'Papeetē',
    currency: 'XPF',
    languages: ['fr'],
    emoji: '🇵🇫',
    emojiU: 'U+1F1F5 U+1F1EB',
    code3l: 'PYF',
    code2l: 'PF',
  },
  {
    country_name: 'Gabon',
    native: 'Gabon',
    phone: '241',
    continent_name: 'AF',
    capital: 'Libreville',
    currency: 'XAF',
    languages: ['fr'],
    emoji: '🇬🇦',
    emojiU: 'U+1F1EC U+1F1E6',
    code3l: 'GAB',
    code2l: 'GA',
  },
  {
    country_name: 'Gambia',
    native: 'Gambia',
    phone: '220',
    continent_name: 'AF',
    capital: 'Banjul',
    currency: 'GMD',
    languages: ['en'],
    emoji: '🇬🇲',
    emojiU: 'U+1F1EC U+1F1F2',
    code3l: 'GMB',
    code2l: 'GM',
  },
  {
    country_name: 'Georgia',
    native: 'საქართველო',
    phone: '995',
    continent_name: 'AS',
    capital: 'Tbilisi',
    currency: 'GEL',
    languages: ['ka'],
    emoji: '🇬🇪',
    emojiU: 'U+1F1EC U+1F1EA',
    code3l: 'GEO',
    code2l: 'GE',
  },
  {
    country_name: 'Germany',
    native: 'Deutschland',
    phone: '49',
    continent_name: 'EU',
    capital: 'Berlin',
    currency: 'EUR',
    languages: ['de'],
    emoji: '🇩🇪',
    emojiU: 'U+1F1E9 U+1F1EA',
    code3l: 'DEU',
    code2l: 'DE',
  },
  {
    country_name: 'Ghana',
    native: 'Ghana',
    phone: '233',
    continent_name: 'AF',
    capital: 'Accra',
    currency: 'GHS',
    languages: ['en'],
    emoji: '🇬🇭',
    emojiU: 'U+1F1EC U+1F1ED',
    code3l: 'GHA',
    code2l: 'GH',
  },
  {
    country_name: 'Gibraltar',
    native: 'Gibraltar',
    phone: '350',
    continent_name: 'EU',
    capital: 'Gibraltar',
    currency: 'GIP',
    languages: ['en'],
    emoji: '🇬🇮',
    emojiU: 'U+1F1EC U+1F1EE',
    code3l: 'GIB',
    code2l: 'GI',
  },
  {
    country_name: 'Greece',
    native: 'Ελλάδα',
    phone: '30',
    continent_name: 'EU',
    capital: 'Athens',
    currency: 'EUR',
    languages: ['el'],
    emoji: '🇬🇷',
    emojiU: 'U+1F1EC U+1F1F7',
    code3l: 'GRC',
    code2l: 'GR',
  },
  {
    country_name: 'Greenland',
    native: 'Kalaallit Nunaat',
    phone: '299',
    continent_name: 'NA',
    capital: 'Nuuk',
    currency: 'DKK',
    languages: ['kl'],
    emoji: '🇬🇱',
    emojiU: 'U+1F1EC U+1F1F1',
    code3l: 'GRL',
    code2l: 'GL',
  },
  {
    country_name: 'Grenada',
    native: 'Grenada',
    phone: '1',
    continent_name: 'NA',
    capital: "St. George's",
    currency: 'XCD',
    languages: ['en'],
    emoji: '🇬🇩',
    emojiU: 'U+1F1EC U+1F1E9',
    code3l: 'GRD',
    code2l: 'GD',
  },
  {
    country_name: 'Guadeloupe',
    native: 'Guadeloupe',
    phone: '590',
    continent_name: 'NA',
    capital: 'Basse-Terre',
    currency: 'EUR',
    languages: ['fr'],
    emoji: '🇬🇵',
    emojiU: 'U+1F1EC U+1F1F5',
    code3l: 'GLP',
    code2l: 'GP',
  },
  {
    country_name: 'Guam',
    native: 'Guam',
    phone: '1',
    continent_name: 'OC',
    capital: 'Hagåtña',
    currency: 'USD',
    languages: ['en', 'ch', 'es'],
    emoji: '🇬🇺',
    emojiU: 'U+1F1EC U+1F1FA',
    code3l: 'GUM',
    code2l: 'GU',
  },
  {
    country_name: 'Guatemala',
    native: 'Guatemala',
    phone: '502',
    continent_name: 'NA',
    capital: 'Guatemala City',
    currency: 'GTQ',
    languages: ['es'],
    emoji: '🇬🇹',
    emojiU: 'U+1F1EC U+1F1F9',
    code3l: 'GTM',
    code2l: 'GT',
  },
  {
    country_name: 'Guernsey',
    native: 'Guernsey',
    phone: '44',
    continent_name: 'EU',
    capital: 'St. Peter Port',
    currency: 'GBP',
    languages: ['en', 'fr'],
    emoji: '🇬🇬',
    emojiU: 'U+1F1EC U+1F1EC',
    code3l: 'GGY',
    code2l: 'GG',
  },
  {
    country_name: 'Guinea',
    native: 'Guinée',
    phone: '224',
    continent_name: 'AF',
    capital: 'Conakry',
    currency: 'GNF',
    languages: ['fr', 'ff'],
    emoji: '🇬🇳',
    emojiU: 'U+1F1EC U+1F1F3',
    code3l: 'GIN',
    code2l: 'GN',
  },
  {
    country_name: 'Guyana',
    native: 'Guyana',
    phone: '592',
    continent_name: 'SA',
    capital: 'Georgetown',
    currency: 'GYD',
    languages: ['en'],
    emoji: '🇬🇾',
    emojiU: 'U+1F1EC U+1F1FE',
    code3l: 'GUY',
    code2l: 'GY',
  },
  {
    country_name: 'Haiti',
    native: 'Haïti',
    phone: '509',
    continent_name: 'NA',
    capital: 'Port-au-Prince',
    currency: 'HTG,USD',
    languages: ['fr', 'ht'],
    emoji: '🇭🇹',
    emojiU: 'U+1F1ED U+1F1F9',
    code3l: 'HTI',
    code2l: 'HT',
  },
  {
    country_name: 'Honduras',
    native: 'Honduras',
    phone: '504',
    continent_name: 'NA',
    capital: 'Tegucigalpa',
    currency: 'HNL',
    languages: ['es'],
    emoji: '🇭🇳',
    emojiU: 'U+1F1ED U+1F1F3',
    code3l: 'HND',
    code2l: 'HN',
  },
  {
    country_name: 'Hong Kong',
    native: '香港',
    phone: '852',
    continent_name: 'AS',
    capital: 'City of Victoria',
    currency: 'HKD',
    languages: ['zh', 'en'],
    emoji: '🇭🇰',
    emojiU: 'U+1F1ED U+1F1F0',
    code3l: 'HKG',
    code2l: 'HK',
  },
  {
    country_name: 'Hungary',
    native: 'Magyarország',
    phone: '36',
    continent_name: 'EU',
    capital: 'Budapest',
    currency: 'HUF',
    languages: ['hu'],
    emoji: '🇭🇺',
    emojiU: 'U+1F1ED U+1F1FA',
    code3l: 'HUN',
    code2l: 'HU',
  },
  {
    country_name: 'Iceland',
    native: 'Ísland',
    phone: '354',
    continent_name: 'EU',
    capital: 'Reykjavik',
    currency: 'ISK',
    languages: ['is'],
    emoji: '🇮🇸',
    emojiU: 'U+1F1EE U+1F1F8',
    code3l: 'ISL',
    code2l: 'IS',
  },
  {
    country_name: 'India',
    native: 'भारत',
    phone: '91',
    continent_name: 'AS',
    capital: 'New Delhi',
    currency: 'INR',
    languages: ['hi', 'en'],
    emoji: '🇮🇳',
    emojiU: 'U+1F1EE U+1F1F3',
    code3l: 'IND',
    code2l: 'IN',
  },
  {
    country_name: 'Indonesia',
    native: 'Indonesia',
    phone: '62',
    continent_name: 'AS',
    capital: 'Jakarta',
    currency: 'IDR',
    languages: ['id'],
    emoji: '🇮🇩',
    emojiU: 'U+1F1EE U+1F1E9',
    code3l: 'IDN',
    code2l: 'ID',
  },
  {
    country_name: 'Iraq',
    native: 'العراق',
    phone: '964',
    continent_name: 'AS',
    capital: 'Baghdad',
    currency: 'IQD',
    languages: ['ar', 'ku'],
    emoji: '🇮🇶',
    emojiU: 'U+1F1EE U+1F1F6',
    code3l: 'IRQ',
    code2l: 'IQ',
  },
  {
    country_name: 'Ireland',
    native: 'Éire',
    phone: '353',
    continent_name: 'EU',
    capital: 'Dublin',
    currency: 'EUR',
    languages: ['ga', 'en'],
    emoji: '🇮🇪',
    emojiU: 'U+1F1EE U+1F1EA',
    code3l: 'IRL',
    code2l: 'IE',
  },
  {
    country_name: 'Isle of Man',
    native: 'Isle of Man',
    phone: '44',
    continent_name: 'EU',
    capital: 'Douglas',
    currency: 'GBP',
    languages: ['en', 'gv'],
    emoji: '🇮🇲',
    emojiU: 'U+1F1EE U+1F1F2',
    code3l: 'IMN',
    code2l: 'IM',
  },
  {
    country_name: 'Israel',
    native: 'יִשְׂרָאֵל',
    phone: '972',
    continent_name: 'AS',
    capital: 'Jerusalem',
    currency: 'ILS',
    languages: ['he', 'ar'],
    emoji: '🇮🇱',
    emojiU: 'U+1F1EE U+1F1F1',
    code3l: 'ISR',
    code2l: 'IL',
  },
  {
    country_name: 'Italy',
    native: 'Italia',
    phone: '39',
    continent_name: 'EU',
    capital: 'Rome',
    currency: 'EUR',
    languages: ['it'],
    emoji: '🇮🇹',
    emojiU: 'U+1F1EE U+1F1F9',
    code3l: 'ITA',
    code2l: 'IT',
  },
  {
    country_name: 'Jamaica',
    native: 'Jamaica',
    phone: '1',
    continent_name: 'NA',
    capital: 'Kingston',
    currency: 'JMD',
    languages: ['en'],
    emoji: '🇯🇲',
    emojiU: 'U+1F1EF U+1F1F2',
    code3l: 'JAM',
    code2l: 'JM',
  },
  {
    country_name: 'Japan',
    native: '日本',
    phone: '81',
    continent_name: 'AS',
    capital: 'Tokyo',
    currency: 'JPY',
    languages: ['ja'],
    emoji: '🇯🇵',
    emojiU: 'U+1F1EF U+1F1F5',
    code3l: 'JPN',
    code2l: 'JP',
  },
  {
    country_name: 'Jersey',
    native: 'Jersey',
    phone: '44',
    continent_name: 'EU',
    capital: 'Saint Helier',
    currency: 'GBP',
    languages: ['en', 'fr'],
    emoji: '🇯🇪',
    emojiU: 'U+1F1EF U+1F1EA',
    code3l: 'JEY',
    code2l: 'JE',
  },
  {
    country_name: 'Jordan',
    native: 'الأردن',
    phone: '962',
    continent_name: 'AS',
    capital: 'Amman',
    currency: 'JOD',
    languages: ['ar'],
    emoji: '🇯🇴',
    emojiU: 'U+1F1EF U+1F1F4',
    code3l: 'JOR',
    code2l: 'JO',
  },
  {
    country_name: 'Kazakhstan',
    native: 'Қазақстан',
    phone: '7',
    continent_name: 'AS',
    capital: 'Astana',
    currency: 'KZT',
    languages: ['kk', 'ru'],
    emoji: '🇰🇿',
    emojiU: 'U+1F1F0 U+1F1FF',
    code3l: 'KAZ',
    code2l: 'KZ',
  },
  {
    country_name: 'Kenya',
    native: 'Kenya',
    phone: '254',
    continent_name: 'AF',
    capital: 'Nairobi',
    currency: 'KES',
    languages: ['en', 'sw'],
    emoji: '🇰🇪',
    emojiU: 'U+1F1F0 U+1F1EA',
    code3l: 'KEN',
    code2l: 'KE',
  },
  {
    country_name: 'Kiribati',
    native: 'Kiribati',
    phone: '686',
    continent_name: 'OC',
    capital: 'South Tarawa',
    currency: 'AUD',
    languages: ['en'],
    emoji: '🇰🇮',
    emojiU: 'U+1F1F0 U+1F1EE',
    code3l: 'KIR',
    code2l: 'KI',
  },
  {
    country_name: 'Kuwait',
    native: 'الكويت',
    phone: '965',
    continent_name: 'AS',
    capital: 'Kuwait City',
    currency: 'KWD',
    languages: ['ar'],
    emoji: '🇰🇼',
    emojiU: 'U+1F1F0 U+1F1FC',
    code3l: 'KWT',
    code2l: 'KW',
  },
  {
    country_name: 'Kyrgyzstan',
    native: 'Кыргызстан',
    phone: '996',
    continent_name: 'AS',
    capital: 'Bishkek',
    currency: 'KGS',
    languages: ['ky', 'ru'],
    emoji: '🇰🇬',
    emojiU: 'U+1F1F0 U+1F1EC',
    code3l: 'KGZ',
    code2l: 'KG',
  },
  {
    country_name: 'Latvia',
    native: 'Latvija',
    phone: '371',
    continent_name: 'EU',
    capital: 'Riga',
    currency: 'EUR',
    languages: ['lv'],
    emoji: '🇱🇻',
    emojiU: 'U+1F1F1 U+1F1FB',
    code3l: 'LVA',
    code2l: 'LV',
  },
  {
    country_name: 'Lebanon',
    native: 'لبنان',
    phone: '961',
    continent_name: 'AS',
    capital: 'Beirut',
    currency: 'LBP',
    languages: ['ar', 'fr'],
    emoji: '🇱🇧',
    emojiU: 'U+1F1F1 U+1F1E7',
    code3l: 'LBN',
    code2l: 'LB',
  },
  {
    country_name: 'Lesotho',
    native: 'Lesotho',
    phone: '266',
    continent_name: 'AF',
    capital: 'Maseru',
    currency: 'LSL,ZAR',
    languages: ['en', 'st'],
    emoji: '🇱🇸',
    emojiU: 'U+1F1F1 U+1F1F8',
    code3l: 'LSO',
    code2l: 'LS',
  },
  {
    country_name: 'Liberia',
    native: 'Liberia',
    phone: '231',
    continent_name: 'AF',
    capital: 'Monrovia',
    currency: 'LRD',
    languages: ['en'],
    emoji: '🇱🇷',
    emojiU: 'U+1F1F1 U+1F1F7',
    code3l: 'LBR',
    code2l: 'LR',
  },
  {
    country_name: 'Libya',
    native: '‏ليبيا',
    phone: '218',
    continent_name: 'AF',
    capital: 'Tripoli',
    currency: 'LYD',
    languages: ['ar'],
    emoji: '🇱🇾',
    emojiU: 'U+1F1F1 U+1F1FE',
    code3l: 'LBY',
    code2l: 'LY',
  },
  {
    country_name: 'Liechtenstein',
    native: 'Liechtenstein',
    phone: '423',
    continent_name: 'EU',
    capital: 'Vaduz',
    currency: 'CHF',
    languages: ['de'],
    emoji: '🇱🇮',
    emojiU: 'U+1F1F1 U+1F1EE',
    code3l: 'LIE',
    code2l: 'LI',
  },
  {
    country_name: 'Lithuania',
    native: 'Lietuva',
    phone: '370',
    continent_name: 'EU',
    capital: 'Vilnius',
    currency: 'EUR',
    languages: ['lt'],
    emoji: '🇱🇹',
    emojiU: 'U+1F1F1 U+1F1F9',
    code3l: 'LTU',
    code2l: 'LT',
  },
  {
    country_name: 'Luxembourg',
    native: 'Luxembourg',
    phone: '352',
    continent_name: 'EU',
    capital: 'Luxembourg',
    currency: 'EUR',
    languages: ['fr', 'de', 'lb'],
    emoji: '🇱🇺',
    emojiU: 'U+1F1F1 U+1F1FA',
    code3l: 'LUX',
    code2l: 'LU',
  },
  {
    country_name: 'Macao',
    native: '澳門',
    phone: '853',
    continent_name: 'AS',
    capital: '',
    currency: 'MOP',
    languages: ['zh', 'pt'],
    emoji: '🇲🇴',
    emojiU: 'U+1F1F2 U+1F1F4',
    code3l: 'MAC',
    code2l: 'MO',
  },
  {
    country_name: 'Madagascar',
    native: 'Madagasikara',
    phone: '261',
    continent_name: 'AF',
    capital: 'Antananarivo',
    currency: 'MGA',
    languages: ['fr', 'mg'],
    emoji: '🇲🇬',
    emojiU: 'U+1F1F2 U+1F1EC',
    code3l: 'MDG',
    code2l: 'MG',
  },
  {
    country_name: 'Malawi',
    native: 'Malawi',
    phone: '265',
    continent_name: 'AF',
    capital: 'Lilongwe',
    currency: 'MWK',
    languages: ['en', 'ny'],
    emoji: '🇲🇼',
    emojiU: 'U+1F1F2 U+1F1FC',
    code3l: 'MWI',
    code2l: 'MW',
  },
  {
    country_name: 'Malaysia',
    native: 'Malaysia',
    phone: '60',
    continent_name: 'AS',
    capital: 'Kuala Lumpur',
    currency: 'MYR',
    languages: ['ms'],
    emoji: '🇲🇾',
    emojiU: 'U+1F1F2 U+1F1FE',
    code3l: 'MYS',
    code2l: 'MY',
  },
  {
    country_name: 'Maldives',
    native: 'Maldives',
    phone: '960',
    continent_name: 'AS',
    capital: 'Malé',
    currency: 'MVR',
    languages: ['dv'],
    emoji: '🇲🇻',
    emojiU: 'U+1F1F2 U+1F1FB',
    code3l: 'MDV',
    code2l: 'MV',
  },
  {
    country_name: 'Mali',
    native: 'Mali',
    phone: '223',
    continent_name: 'AF',
    capital: 'Bamako',
    currency: 'XOF',
    languages: ['fr'],
    emoji: '🇲🇱',
    emojiU: 'U+1F1F2 U+1F1F1',
    code3l: 'MLI',
    code2l: 'ML',
  },
  {
    country_name: 'Malta',
    native: 'Malta',
    phone: '356',
    continent_name: 'EU',
    capital: 'Valletta',
    currency: 'EUR',
    languages: ['mt', 'en'],
    emoji: '🇲🇹',
    emojiU: 'U+1F1F2 U+1F1F9',
    code3l: 'MLT',
    code2l: 'MT',
  },
  {
    country_name: 'Marshall Islands',
    native: 'M̧ajeļ',
    phone: '692',
    continent_name: 'OC',
    capital: 'Majuro',
    currency: 'USD',
    languages: ['en', 'mh'],
    emoji: '🇲🇭',
    emojiU: 'U+1F1F2 U+1F1ED',
    code3l: 'MHL',
    code2l: 'MH',
  },
  {
    country_name: 'Martinique',
    native: 'Martinique',
    phone: '596',
    continent_name: 'NA',
    capital: 'Fort-de-France',
    currency: 'EUR',
    languages: ['fr'],
    emoji: '🇲🇶',
    emojiU: 'U+1F1F2 U+1F1F6',
    code3l: 'MTQ',
    code2l: 'MQ',
  },
  {
    country_name: 'Mauritania',
    native: 'موريتانيا',
    phone: '222',
    continent_name: 'AF',
    capital: 'Nouakchott',
    currency: 'MRU',
    languages: ['ar'],
    emoji: '🇲🇷',
    emojiU: 'U+1F1F2 U+1F1F7',
    code3l: 'MRT',
    code2l: 'MR',
  },
  {
    country_name: 'Mauritius',
    native: 'Maurice',
    phone: '230',
    continent_name: 'AF',
    capital: 'Port Louis',
    currency: 'MUR',
    languages: ['en'],
    emoji: '🇲🇺',
    emojiU: 'U+1F1F2 U+1F1FA',
    code3l: 'MUS',
    code2l: 'MU',
  },
  {
    country_name: 'Mayotte',
    native: 'Mayotte',
    phone: '262',
    continent_name: 'AF',
    capital: 'Mamoudzou',
    currency: 'EUR',
    languages: ['fr'],
    emoji: '🇾🇹',
    emojiU: 'U+1F1FE U+1F1F9',
    code3l: 'MYT',
    code2l: 'YT',
  },
  {
    country_name: 'Mexico',
    native: 'México',
    phone: '52',
    continent_name: 'NA',
    capital: 'Mexico City',
    currency: 'MXN',
    languages: ['es'],
    emoji: '🇲🇽',
    emojiU: 'U+1F1F2 U+1F1FD',
    code3l: 'MEX',
    code2l: 'MX',
  },
  {
    country_name: 'Monaco',
    native: 'Monaco',
    phone: '377',
    continent_name: 'EU',
    capital: 'Monaco',
    currency: 'EUR',
    languages: ['fr'],
    emoji: '🇲🇨',
    emojiU: 'U+1F1F2 U+1F1E8',
    code3l: 'MCO',
    code2l: 'MC',
  },
  {
    country_name: 'Mongolia',
    native: 'Монгол улс',
    phone: '976',
    continent_name: 'AS',
    capital: 'Ulan Bator',
    currency: 'MNT',
    languages: ['mn'],
    emoji: '🇲🇳',
    emojiU: 'U+1F1F2 U+1F1F3',
    code3l: 'MNG',
    code2l: 'MN',
  },
  {
    country_name: 'Montenegro',
    native: 'Црна Гора',
    phone: '382',
    continent_name: 'EU',
    capital: 'Podgorica',
    currency: 'EUR',
    languages: ['sr', 'bs', 'sq', 'hr'],
    emoji: '🇲🇪',
    emojiU: 'U+1F1F2 U+1F1EA',
    code3l: 'MNE',
    code2l: 'ME',
  },
  {
    country_name: 'Montserrat',
    native: 'Montserrat',
    phone: '1',
    continent_name: 'NA',
    capital: 'Plymouth',
    currency: 'XCD',
    languages: ['en'],
    emoji: '🇲🇸',
    emojiU: 'U+1F1F2 U+1F1F8',
    code3l: 'MSR',
    code2l: 'MS',
  },
  {
    country_name: 'Morocco',
    native: 'المغرب',
    phone: '212',
    continent_name: 'AF',
    capital: 'Rabat',
    currency: 'MAD',
    languages: ['ar'],
    emoji: '🇲🇦',
    emojiU: 'U+1F1F2 U+1F1E6',
    code3l: 'MAR',
    code2l: 'MA',
  },
  {
    country_name: 'Mozambique',
    native: 'Moçambique',
    phone: '258',
    continent_name: 'AF',
    capital: 'Maputo',
    currency: 'MZN',
    languages: ['pt'],
    emoji: '🇲🇿',
    emojiU: 'U+1F1F2 U+1F1FF',
    code3l: 'MOZ',
    code2l: 'MZ',
  },
  {
    country_name: 'Namibia',
    native: 'Namibia',
    phone: '264',
    continent_name: 'AF',
    capital: 'Windhoek',
    currency: 'NAD,ZAR',
    languages: ['en', 'af'],
    emoji: '🇳🇦',
    emojiU: 'U+1F1F3 U+1F1E6',
    code3l: 'NAM',
    code2l: 'NA',
  },
  {
    country_name: 'Nauru',
    native: 'Nauru',
    phone: '674',
    continent_name: 'OC',
    capital: 'Yaren',
    currency: 'AUD',
    languages: ['en', 'na'],
    emoji: '🇳🇷',
    emojiU: 'U+1F1F3 U+1F1F7',
    code3l: 'NRU',
    code2l: 'NR',
  },
  {
    country_name: 'Nepal',
    native: 'नपल',
    phone: '977',
    continent_name: 'AS',
    capital: 'Kathmandu',
    currency: 'NPR',
    languages: ['ne'],
    emoji: '🇳🇵',
    emojiU: 'U+1F1F3 U+1F1F5',
    code3l: 'NPL',
    code2l: 'NP',
  },
  {
    country_name: 'Netherlands',
    native: 'Nederland',
    phone: '31',
    continent_name: 'EU',
    capital: 'Amsterdam',
    currency: 'EUR',
    languages: ['nl'],
    emoji: '🇳🇱',
    emojiU: 'U+1F1F3 U+1F1F1',
    code3l: 'NLD',
    code2l: 'NL',
  },
  {
    country_name: 'New Caledonia',
    native: 'Nouvelle-Calédonie',
    phone: '687',
    continent_name: 'OC',
    capital: 'Nouméa',
    currency: 'XPF',
    languages: ['fr'],
    emoji: '🇳🇨',
    emojiU: 'U+1F1F3 U+1F1E8',
    code3l: 'NCL',
    code2l: 'NC',
  },
  {
    country_name: 'New Zealand',
    native: 'New Zealand',
    phone: '64',
    continent_name: 'OC',
    capital: 'Wellington',
    currency: 'NZD',
    languages: ['en', 'mi'],
    emoji: '🇳🇿',
    emojiU: 'U+1F1F3 U+1F1FF',
    code3l: 'NZL',
    code2l: 'NZ',
  },
  {
    country_name: 'Nicaragua',
    native: 'Nicaragua',
    phone: '505',
    continent_name: 'NA',
    capital: 'Managua',
    currency: 'NIO',
    languages: ['es'],
    emoji: '🇳🇮',
    emojiU: 'U+1F1F3 U+1F1EE',
    code3l: 'NIC',
    code2l: 'NI',
  },
  {
    country_name: 'Niger',
    native: 'Niger',
    phone: '227',
    continent_name: 'AF',
    capital: 'Niamey',
    currency: 'XOF',
    languages: ['fr'],
    emoji: '🇳🇪',
    emojiU: 'U+1F1F3 U+1F1EA',
    code3l: 'NER',
    code2l: 'NE',
  },
  {
    country_name: 'Niue',
    native: 'Niuē',
    phone: '683',
    continent_name: 'OC',
    capital: 'Alofi',
    currency: 'NZD',
    languages: ['en'],
    emoji: '🇳🇺',
    emojiU: 'U+1F1F3 U+1F1FA',
    code3l: 'NIU',
    code2l: 'NU',
  },
  {
    country_name: 'Norfolk Island',
    native: 'Norfolk Island',
    phone: '672',
    continent_name: 'OC',
    capital: 'Kingston',
    currency: 'AUD',
    languages: ['en'],
    emoji: '🇳🇫',
    emojiU: 'U+1F1F3 U+1F1EB',
    code3l: 'NFK',
    code2l: 'NF',
  },
  {
    country_name: 'North Macedonia',
    native: 'Северна Македонија',
    phone: '389',
    continent_name: 'EU',
    capital: 'Skopje',
    currency: 'MKD',
    languages: ['mk'],
    emoji: '🇲🇰',
    emojiU: 'U+1F1F2 U+1F1F0',
    code3l: 'MKD',
    code2l: 'MK',
  },
  {
    country_name: 'Northern Mariana Islands',
    native: 'Northern Mariana Islands',
    phone: '1',
    continent_name: 'OC',
    capital: 'Saipan',
    currency: 'USD',
    languages: ['en', 'ch'],
    emoji: '🇲🇵',
    emojiU: 'U+1F1F2 U+1F1F5',
    code3l: 'MNP',
    code2l: 'MP',
  },
  {
    country_name: 'Norway',
    native: 'Norge',
    phone: '47',
    continent_name: 'EU',
    capital: 'Oslo',
    currency: 'NOK',
    languages: ['no', 'nb', 'nn'],
    emoji: '🇳🇴',
    emojiU: 'U+1F1F3 U+1F1F4',
    code3l: 'NOR',
    code2l: 'NO',
  },
  {
    country_name: 'Oman',
    native: 'عمان',
    phone: '968',
    continent_name: 'AS',
    capital: 'Muscat',
    currency: 'OMR',
    languages: ['ar'],
    emoji: '🇴🇲',
    emojiU: 'U+1F1F4 U+1F1F2',
    code3l: 'OMN',
    code2l: 'OM',
  },
  {
    country_name: 'Pakistan',
    native: 'Pakistan',
    phone: '92',
    continent_name: 'AS',
    capital: 'Islamabad',
    currency: 'PKR',
    languages: ['en', 'ur'],
    emoji: '🇵🇰',
    emojiU: 'U+1F1F5 U+1F1F0',
    code3l: 'PAK',
    code2l: 'PK',
  },
  {
    country_name: 'Palau',
    native: 'Palau',
    phone: '680',
    continent_name: 'OC',
    capital: 'Ngerulmud',
    currency: 'USD',
    languages: ['en'],
    emoji: '🇵🇼',
    emojiU: 'U+1F1F5 U+1F1FC',
    code3l: 'PLW',
    code2l: 'PW',
  },
  {
    country_name: 'Panama',
    native: 'Panamá',
    phone: '507',
    continent_name: 'NA',
    capital: 'Panama City',
    currency: 'PAB,USD',
    languages: ['es'],
    emoji: '🇵🇦',
    emojiU: 'U+1F1F5 U+1F1E6',
    code3l: 'PAN',
    code2l: 'PA',
  },
  {
    country_name: 'Paraguay',
    native: 'Paraguay',
    phone: '595',
    continent_name: 'SA',
    capital: 'Asunción',
    currency: 'PYG',
    languages: ['es', 'gn'],
    emoji: '🇵🇾',
    emojiU: 'U+1F1F5 U+1F1FE',
    code3l: 'PRY',
    code2l: 'PY',
  },
  {
    country_name: 'Peru',
    native: 'Perú',
    phone: '51',
    continent_name: 'SA',
    capital: 'Lima',
    currency: 'PEN',
    languages: ['es'],
    emoji: '🇵🇪',
    emojiU: 'U+1F1F5 U+1F1EA',
    code3l: 'PER',
    code2l: 'PE',
  },
  {
    country_name: 'Philippines',
    native: 'Pilipinas',
    phone: '63',
    continent_name: 'AS',
    capital: 'Manila',
    currency: 'PHP',
    languages: ['en'],
    emoji: '🇵🇭',
    emojiU: 'U+1F1F5 U+1F1ED',
    code3l: 'PHL',
    code2l: 'PH',
  },
  {
    country_name: 'Pitcairn Islands',
    native: 'Pitcairn Islands',
    phone: '64',
    continent_name: 'OC',
    capital: 'Adamstown',
    currency: 'NZD',
    languages: ['en'],
    emoji: '🇵🇳',
    emojiU: 'U+1F1F5 U+1F1F3',
    code3l: 'PCN',
    code2l: 'PN',
  },
  {
    country_name: 'Poland',
    native: 'Polska',
    phone: '48',
    continent_name: 'EU',
    capital: 'Warsaw',
    currency: 'PLN',
    languages: ['pl'],
    emoji: '🇵🇱',
    emojiU: 'U+1F1F5 U+1F1F1',
    code3l: 'POL',
    code2l: 'PL',
  },
  {
    country_name: 'Portugal',
    native: 'Portugal',
    phone: '351',
    continent_name: 'EU',
    capital: 'Lisbon',
    currency: 'EUR',
    languages: ['pt'],
    emoji: '🇵🇹',
    emojiU: 'U+1F1F5 U+1F1F9',
    code3l: 'PRT',
    code2l: 'PT',
  },
  {
    country_name: 'Puerto Rico',
    native: 'Puerto Rico',
    phone: '1',
    continent_name: 'NA',
    capital: 'San Juan',
    currency: 'USD',
    languages: ['es', 'en'],
    emoji: '🇵🇷',
    emojiU: 'U+1F1F5 U+1F1F7',
    code3l: 'PRI',
    code2l: 'PR',
  },
  {
    country_name: 'Qatar',
    native: 'قطر',
    phone: '974',
    continent_name: 'AS',
    capital: 'Doha',
    currency: 'QAR',
    languages: ['ar'],
    emoji: '🇶🇦',
    emojiU: 'U+1F1F6 U+1F1E6',
    code3l: 'QAT',
    code2l: 'QA',
  },
  {
    country_name: 'Réunion',
    native: 'La Réunion',
    phone: '262',
    continent_name: 'AF',
    capital: 'Saint-Denis',
    currency: 'EUR',
    languages: ['fr'],
    emoji: '🇷🇪',
    emojiU: 'U+1F1F7 U+1F1EA',
    code3l: 'REU',
    code2l: 'RE',
  },
  {
    country_name: 'Romania',
    native: 'România',
    phone: '40',
    continent_name: 'EU',
    capital: 'Bucharest',
    currency: 'RON',
    languages: ['ro'],
    emoji: '🇷🇴',
    emojiU: 'U+1F1F7 U+1F1F4',
    code3l: 'ROU',
    code2l: 'RO',
  },
  {
    country_name: 'Rwanda',
    native: 'Rwanda',
    phone: '250',
    continent_name: 'AF',
    capital: 'Kigali',
    currency: 'RWF',
    languages: ['rw', 'en', 'fr'],
    emoji: '🇷🇼',
    emojiU: 'U+1F1F7 U+1F1FC',
    code3l: 'RWA',
    code2l: 'RW',
  },
  {
    country_name: 'Saint Barthélemy',
    native: 'Saint-Barthélemy',
    phone: '590',
    continent_name: 'NA',
    capital: 'Gustavia',
    currency: 'EUR',
    languages: ['fr'],
    emoji: '🇧🇱',
    emojiU: 'U+1F1E7 U+1F1F1',
    code3l: 'BLM',
    code2l: 'BL',
  },
  {
    country_name: 'Saint Kitts and Nevis',
    native: 'Saint Kitts and Nevis',
    phone: '1',
    continent_name: 'NA',
    capital: 'Basseterre',
    currency: 'XCD',
    languages: ['en'],
    emoji: '🇰🇳',
    emojiU: 'U+1F1F0 U+1F1F3',
    code3l: 'KNA',
    code2l: 'KN',
  },
  {
    country_name: 'Saint Lucia',
    native: 'Saint Lucia',
    phone: '1',
    continent_name: 'NA',
    capital: 'Castries',
    currency: 'XCD',
    languages: ['en'],
    emoji: '🇱🇨',
    emojiU: 'U+1F1F1 U+1F1E8',
    code3l: 'LCA',
    code2l: 'LC',
  },
  {
    country_name: 'Saint Martin',
    native: 'Saint-Martin',
    phone: '590',
    continent_name: 'NA',
    capital: 'Marigot',
    currency: 'EUR',
    languages: ['en', 'fr', 'nl'],
    emoji: '🇲🇫',
    emojiU: 'U+1F1F2 U+1F1EB',
    code3l: 'MAF',
    code2l: 'MF',
  },
  {
    country_name: 'Saint Pierre and Miquelon',
    native: 'Saint-Pierre-et-Miquelon',
    phone: '508',
    continent_name: 'NA',
    capital: 'Saint-Pierre',
    currency: 'EUR',
    languages: ['fr'],
    emoji: '🇵🇲',
    emojiU: 'U+1F1F5 U+1F1F2',
    code3l: 'SPM',
    code2l: 'PM',
  },
  {
    country_name: 'Saint Vincent and the Grenadines',
    native: 'Saint Vincent and the Grenadines',
    phone: '1',
    continent_name: 'NA',
    capital: 'Kingstown',
    currency: 'XCD',
    languages: ['en'],
    emoji: '🇻🇨',
    emojiU: 'U+1F1FB U+1F1E8',
    code3l: 'VCT',
    code2l: 'VC',
  },
  {
    country_name: 'Samoa',
    native: 'Samoa',
    phone: '685',
    continent_name: 'OC',
    capital: 'Apia',
    currency: 'WST',
    languages: ['sm', 'en'],
    emoji: '🇼🇸',
    emojiU: 'U+1F1FC U+1F1F8',
    code3l: 'WSM',
    code2l: 'WS',
  },
  {
    country_name: 'San Marino',
    native: 'San Marino',
    phone: '378',
    continent_name: 'EU',
    capital: 'City of San Marino',
    currency: 'EUR',
    languages: ['it'],
    emoji: '🇸🇲',
    emojiU: 'U+1F1F8 U+1F1F2',
    code3l: 'SMR',
    code2l: 'SM',
  },
  {
    country_name: 'Saudi Arabia',
    native: 'العربية السعودية',
    phone: '966',
    continent_name: 'AS',
    capital: 'Riyadh',
    currency: 'SAR',
    languages: ['ar'],
    emoji: '🇸🇦',
    emojiU: 'U+1F1F8 U+1F1E6',
    code3l: 'SAU',
    code2l: 'SA',
  },
  {
    country_name: 'Senegal',
    native: 'Sénégal',
    phone: '221',
    continent_name: 'AF',
    capital: 'Dakar',
    currency: 'XOF',
    languages: ['fr'],
    emoji: '🇸🇳',
    emojiU: 'U+1F1F8 U+1F1F3',
    code3l: 'SEN',
    code2l: 'SN',
  },
  {
    country_name: 'Serbia',
    native: 'Србија',
    phone: '381',
    continent_name: 'EU',
    capital: 'Belgrade',
    currency: 'RSD',
    languages: ['sr'],
    emoji: '🇷🇸',
    emojiU: 'U+1F1F7 U+1F1F8',
    code3l: 'SRB',
    code2l: 'RS',
  },
  {
    country_name: 'Seychelles',
    native: 'Seychelles',
    phone: '248',
    continent_name: 'AF',
    capital: 'Victoria',
    currency: 'SCR',
    languages: ['fr', 'en'],
    emoji: '🇸🇨',
    emojiU: 'U+1F1F8 U+1F1E8',
    code3l: 'SYC',
    code2l: 'SC',
  },
  {
    country_name: 'Sierra Leone',
    native: 'Sierra Leone',
    phone: '232',
    continent_name: 'AF',
    capital: 'Freetown',
    currency: 'SLL',
    languages: ['en'],
    emoji: '🇸🇱',
    emojiU: 'U+1F1F8 U+1F1F1',
    code3l: 'SLE',
    code2l: 'SL',
  },
  {
    country_name: 'Singapore',
    native: 'Singapore',
    phone: '65',
    continent_name: 'AS',
    capital: 'Singapore',
    currency: 'SGD',
    languages: ['en', 'ms', 'ta', 'zh'],
    emoji: '🇸🇬',
    emojiU: 'U+1F1F8 U+1F1EC',
    code3l: 'SGP',
    code2l: 'SG',
  },
  {
    country_name: 'Sint Maarten',
    native: 'Sint Maarten',
    phone: '1',
    continent_name: 'NA',
    capital: 'Philipsburg',
    currency: 'ANG',
    languages: ['nl', 'en'],
    emoji: '🇸🇽',
    emojiU: 'U+1F1F8 U+1F1FD',
    code3l: 'SXM',
    code2l: 'SX',
  },
  {
    country_name: 'Slovakia',
    native: 'Slovensko',
    phone: '421',
    continent_name: 'EU',
    capital: 'Bratislava',
    currency: 'EUR',
    languages: ['sk'],
    emoji: '🇸🇰',
    emojiU: 'U+1F1F8 U+1F1F0',
    code3l: 'SVK',
    code2l: 'SK',
  },
  {
    country_name: 'Slovenia',
    native: 'Slovenija',
    phone: '386',
    continent_name: 'EU',
    capital: 'Ljubljana',
    currency: 'EUR',
    languages: ['sl'],
    emoji: '🇸🇮',
    emojiU: 'U+1F1F8 U+1F1EE',
    code3l: 'SVN',
    code2l: 'SI',
  },
  {
    country_name: 'Solomon Islands',
    native: 'Solomon Islands',
    phone: '677',
    continent_name: 'OC',
    capital: 'Honiara',
    currency: 'SBD',
    languages: ['en'],
    emoji: '🇸🇧',
    emojiU: 'U+1F1F8 U+1F1E7',
    code3l: 'SLB',
    code2l: 'SB',
  },
  {
    country_name: 'Somalia',
    native: 'Soomaaliya',
    phone: '252',
    continent_name: 'AF',
    capital: 'Mogadishu',
    currency: 'SOS',
    languages: ['so', 'ar'],
    emoji: '🇸🇴',
    emojiU: 'U+1F1F8 U+1F1F4',
    code3l: 'SOM',
    code2l: 'SO',
  },
  {
    country_name: 'South Africa',
    native: 'South Africa',
    phone: '27',
    continent_name: 'AF',
    capital: 'Pretoria',
    currency: 'ZAR',
    languages: ['af', 'en', 'nr', 'st', 'ss', 'tn', 'ts', 've', 'xh', 'zu'],
    emoji: '🇿🇦',
    emojiU: 'U+1F1FF U+1F1E6',
    code3l: 'ZAF',
    code2l: 'ZA',
  },
  {
    country_name: 'Spain',
    native: 'España',
    phone: '34',
    continent_name: 'EU',
    capital: 'Madrid',
    currency: 'EUR',
    languages: ['es', 'eu', 'ca', 'gl', 'oc'],
    emoji: '🇪🇸',
    emojiU: 'U+1F1EA U+1F1F8',
    code3l: 'ESP',
    code2l: 'ES',
  },
  {
    country_name: 'Sri Lanka',
    native: 'śrī laṃkāva',
    phone: '94',
    continent_name: 'AS',
    capital: 'Colombo',
    currency: 'LKR',
    languages: ['si', 'ta'],
    emoji: '🇱🇰',
    emojiU: 'U+1F1F1 U+1F1F0',
    code3l: 'LKA',
    code2l: 'LK',
  },
  {
    country_name: 'Sudan',
    native: 'السودان',
    phone: '249',
    continent_name: 'AF',
    capital: 'Khartoum',
    currency: 'SDG',
    languages: ['ar', 'en'],
    emoji: '🇸🇩',
    emojiU: 'U+1F1F8 U+1F1E9',
    code3l: 'SDN',
    code2l: 'SD',
  },
  {
    country_name: 'Svalbard and Jan Mayen',
    native: 'Svalbard og Jan Mayen',
    phone: '47',
    continent_name: 'EU',
    capital: 'Longyearbyen',
    currency: 'NOK',
    languages: ['no'],
    emoji: '🇸🇯',
    emojiU: 'U+1F1F8 U+1F1EF',
    code3l: 'SJM',
    code2l: 'SJ',
  },
  {
    country_name: 'Sweden',
    native: 'Sverige',
    phone: '46',
    continent_name: 'EU',
    capital: 'Stockholm',
    currency: 'SEK',
    languages: ['sv'],
    emoji: '🇸🇪',
    emojiU: 'U+1F1F8 U+1F1EA',
    code3l: 'SWE',
    code2l: 'SE',
  },
  {
    country_name: 'Switzerland',
    native: 'Schweiz',
    phone: '41',
    continent_name: 'EU',
    capital: 'Bern',
    currency: 'CHE,CHF,CHW',
    languages: ['de', 'fr', 'it'],
    emoji: '🇨🇭',
    emojiU: 'U+1F1E8 U+1F1ED',
    code3l: 'CHE',
    code2l: 'CH',
  },
  {
    country_name: 'Taiwan',
    native: '臺灣',
    phone: '886',
    continent_name: 'AS',
    capital: 'Taipei',
    currency: 'TWD',
    languages: ['zh'],
    emoji: '🇹🇼',
    emojiU: 'U+1F1F9 U+1F1FC',
    code3l: 'TWN',
    code2l: 'TW',
  },
  {
    country_name: 'Tajikistan',
    native: 'Тоҷикистон',
    phone: '992',
    continent_name: 'AS',
    capital: 'Dushanbe',
    currency: 'TJS',
    languages: ['tg', 'ru'],
    emoji: '🇹🇯',
    emojiU: 'U+1F1F9 U+1F1EF',
    code3l: 'TJK',
    code2l: 'TJ',
  },
  {
    country_name: 'Thailand',
    native: 'ประเทศไทย',
    phone: '66',
    continent_name: 'AS',
    capital: 'Bangkok',
    currency: 'THB',
    languages: ['th'],
    emoji: '🇹🇭',
    emojiU: 'U+1F1F9 U+1F1ED',
    code3l: 'THA',
    code2l: 'TH',
  },
  {
    country_name: 'East Timor',
    native: 'Timor-Leste',
    phone: '670',
    continent_name: 'OC',
    capital: 'Dili',
    currency: 'USD',
    languages: ['pt'],
    emoji: '🇹🇱',
    emojiU: 'U+1F1F9 U+1F1F1',
    code3l: 'TLS',
    code2l: 'TL',
  },
  {
    country_name: 'Togo',
    native: 'Togo',
    phone: '228',
    continent_name: 'AF',
    capital: 'Lomé',
    currency: 'XOF',
    languages: ['fr'],
    emoji: '🇹🇬',
    emojiU: 'U+1F1F9 U+1F1EC',
    code3l: 'TGO',
    code2l: 'TG',
  },
  {
    country_name: 'Tonga',
    native: 'Tonga',
    phone: '676',
    continent_name: 'OC',
    capital: "Nuku'alofa",
    currency: 'TOP',
    languages: ['en', 'to'],
    emoji: '🇹🇴',
    emojiU: 'U+1F1F9 U+1F1F4',
    code3l: 'TON',
    code2l: 'TO',
  },
  {
    country_name: 'Trinidad and Tobago',
    native: 'Trinidad and Tobago',
    phone: '1',
    continent_name: 'NA',
    capital: 'Port of Spain',
    currency: 'TTD',
    languages: ['en'],
    emoji: '🇹🇹',
    emojiU: 'U+1F1F9 U+1F1F9',
    code3l: 'TTO',
    code2l: 'TT',
  },
  {
    country_name: 'Tunisia',
    native: 'تونس',
    phone: '216',
    continent_name: 'AF',
    capital: 'Tunis',
    currency: 'TND',
    languages: ['ar'],
    emoji: '🇹🇳',
    emojiU: 'U+1F1F9 U+1F1F3',
    code3l: 'TUN',
    code2l: 'TN',
  },
  {
    country_name: 'Turkey',
    native: 'Türkiye',
    phone: '90',
    continent_name: 'AS',
    capital: 'Ankara',
    currency: 'TRY',
    languages: ['tr'],
    emoji: '🇹🇷',
    emojiU: 'U+1F1F9 U+1F1F7',
    code3l: 'TUR',
    code2l: 'TR',
  },
  {
    country_name: 'Turkmenistan',
    native: 'Türkmenistan',
    phone: '993',
    continent_name: 'AS',
    capital: 'Ashgabat',
    currency: 'TMT',
    languages: ['tk', 'ru'],
    emoji: '🇹🇲',
    emojiU: 'U+1F1F9 U+1F1F2',
    code3l: 'TKM',
    code2l: 'TM',
  },
  {
    country_name: 'Turks and Caicos Islands',
    native: 'Turks and Caicos Islands',
    phone: '1',
    continent_name: 'NA',
    capital: 'Cockburn Town',
    currency: 'USD',
    languages: ['en'],
    emoji: '🇹🇨',
    emojiU: 'U+1F1F9 U+1F1E8',
    code3l: 'TCA',
    code2l: 'TC',
  },
  {
    country_name: 'Tuvalu',
    native: 'Tuvalu',
    phone: '688',
    continent_name: 'OC',
    capital: 'Funafuti',
    currency: 'AUD',
    languages: ['en'],
    emoji: '🇹🇻',
    emojiU: 'U+1F1F9 U+1F1FB',
    code3l: 'TUV',
    code2l: 'TV',
  },
  {
    country_name: 'Uganda',
    native: 'Uganda',
    phone: '256',
    continent_name: 'AF',
    capital: 'Kampala',
    currency: 'UGX',
    languages: ['en', 'sw'],
    emoji: '🇺🇬',
    emojiU: 'U+1F1FA U+1F1EC',
    code3l: 'UGA',
    code2l: 'UG',
  },
  {
    country_name: 'Ukraine',
    native: 'Україна',
    phone: '380',
    continent_name: 'EU',
    capital: 'Kyiv',
    currency: 'UAH',
    languages: ['uk'],
    emoji: '🇺🇦',
    emojiU: 'U+1F1FA U+1F1E6',
    code3l: 'UKR',
    code2l: 'UA',
  },
  {
    country_name: 'United Arab Emirates',
    native: 'دولة الإمارات العربية المتحدة',
    phone: '971',
    continent_name: 'AS',
    capital: 'Abu Dhabi',
    currency: 'AED',
    languages: ['ar'],
    emoji: '🇦🇪',
    emojiU: 'U+1F1E6 U+1F1EA',
    code3l: 'ARE',
    code2l: 'AE',
  },
  {
    country_name: 'United Kingdom',
    native: 'United Kingdom',
    phone: '44',
    continent_name: 'EU',
    capital: 'London',
    currency: 'GBP',
    languages: ['en'],
    emoji: '🇬🇧',
    emojiU: 'U+1F1EC U+1F1E7',
    code3l: 'GBR',
    code2l: 'GB',
  },
  {
    country_name: 'U.S. Minor Outlying Islands',
    native: 'United States Minor Outlying Islands',
    phone: '1',
    continent_name: 'OC',
    capital: '',
    currency: 'USD',
    languages: ['en'],
    emoji: '🇺🇲',
    emojiU: 'U+1F1FA U+1F1F2',
    code3l: 'UMI',
    code2l: 'UM',
  },
  {
    country_name: 'Uruguay',
    native: 'Uruguay',
    phone: '598',
    continent_name: 'SA',
    capital: 'Montevideo',
    currency: 'UYI,UYU',
    languages: ['es'],
    emoji: '🇺🇾',
    emojiU: 'U+1F1FA U+1F1FE',
    code3l: 'URY',
    code2l: 'UY',
  },
  {
    country_name: 'Uzbekistan',
    native: 'O‘zbekiston',
    phone: '998',
    continent_name: 'AS',
    capital: 'Tashkent',
    currency: 'UZS',
    languages: ['uz', 'ru'],
    emoji: '🇺🇿',
    emojiU: 'U+1F1FA U+1F1FF',
    code3l: 'UZB',
    code2l: 'UZ',
  },
  {
    country_name: 'Vanuatu',
    native: 'Vanuatu',
    phone: '678',
    continent_name: 'OC',
    capital: 'Port Vila',
    currency: 'VUV',
    languages: ['bi', 'en', 'fr'],
    emoji: '🇻🇺',
    emojiU: 'U+1F1FB U+1F1FA',
    code3l: 'VUT',
    code2l: 'VU',
  },
  {
    country_name: 'Wallis and Futuna',
    native: 'Wallis et Futuna',
    phone: '681',
    continent_name: 'OC',
    capital: 'Mata-Utu',
    currency: 'XPF',
    languages: ['fr'],
    emoji: '🇼🇫',
    emojiU: 'U+1F1FC U+1F1EB',
    code3l: 'WLF',
    code2l: 'WF',
  },
  {
    country_name: 'Western Sahara',
    native: 'الصحراء الغربية',
    phone: '212',
    continent_name: 'AF',
    capital: 'El Aaiún',
    currency: 'MAD,DZD,MRU',
    languages: ['es'],
    emoji: '🇪🇭',
    emojiU: 'U+1F1EA U+1F1ED',
    code3l: 'ESH',
    code2l: 'EH',
  },
  {
    country_name: 'Yemen',
    native: 'اليَمَن',
    phone: '967',
    continent_name: 'AS',
    capital: "Sana'a",
    currency: 'YER',
    languages: ['ar'],
    emoji: '🇾🇪',
    emojiU: 'U+1F1FE U+1F1EA',
    code3l: 'YEM',
    code2l: 'YE',
  },
  {
    country_name: 'Zambia',
    native: 'Zambia',
    phone: '260',
    continent_name: 'AF',
    capital: 'Lusaka',
    currency: 'ZMW',
    languages: ['en'],
    emoji: '🇿🇲',
    emojiU: 'U+1F1FF U+1F1F2',
    code3l: 'ZMB',
    code2l: 'ZM',
  },
  {
    country_name: 'Zimbabwe',
    native: 'Zimbabwe',
    phone: '263',
    continent_name: 'AF',
    capital: 'Harare',
    currency: 'USD,ZAR,BWP,GBP,AUD,CNY,INR,JPY',
    languages: ['en', 'sn', 'nd'],
    emoji: '🇿🇼',
    emojiU: 'U+1F1FF U+1F1FC',
    code3l: 'ZWE',
    code2l: 'ZW',
  },
  {
    country_name: 'Republic of the Congo',
    native: 'République du Congo',
    phone: '242',
    continent_name: 'AF',
    capital: 'Brazzaville',
    currency: 'XAF',
    languages: ['fr', 'ln'],
    emoji: '🇨🇬',
    emojiU: 'U+1F1E8 U+1F1EC',
    code3l: 'COG',
    code2l: 'CG',
  },
  {
    country_name: 'Czech Republic',
    native: 'Česká republika',
    phone: '420',
    continent_name: 'EU',
    capital: 'Prague',
    currency: 'CZK',
    languages: ['cs', 'sk'],
    emoji: '🇨🇿',
    emojiU: 'U+1F1E8 U+1F1FF',
    code3l: 'CZE',
    code2l: 'CZ',
  },
  {
    country_name: 'Dominican Republic',
    native: 'República Dominicana',
    phone: '1',
    continent_name: 'NA',
    capital: 'Santo Domingo',
    currency: 'DOP',
    languages: ['es'],
    emoji: '🇩🇴',
    emojiU: 'U+1F1E9 U+1F1F4',
    code3l: 'DOM',
    code2l: 'DO',
  },
  {
    country_name: 'Equatorial Guinea',
    native: 'Guinea Ecuatorial',
    phone: '240',
    continent_name: 'AF',
    capital: 'Malabo',
    currency: 'XAF',
    languages: ['es', 'fr'],
    emoji: '🇬🇶',
    emojiU: 'U+1F1EC U+1F1F6',
    code3l: 'GNQ',
    code2l: 'GQ',
  },
  {
    country_name: 'South Georgia and the South Sandwich Islands',
    native: 'South Georgia',
    phone: '500',
    continent_name: 'AN',
    capital: 'King Edward Point',
    currency: 'GBP',
    languages: ['en'],
    emoji: '🇬🇸',
    emojiU: 'U+1F1EC U+1F1F8',
    code3l: 'SGS',
    code2l: 'GS',
  },
  {
    country_name: 'Guinea-Bissau',
    native: 'Guiné-Bissau',
    phone: '245',
    continent_name: 'AF',
    capital: 'Bissau',
    currency: 'XOF',
    languages: ['pt'],
    emoji: '🇬🇼',
    emojiU: 'U+1F1EC U+1F1FC',
    code3l: 'GNB',
    code2l: 'GW',
  },
  {
    country_name: 'Heard Island and McDonald Islands',
    native: 'Heard Island and McDonald Islands',
    phone: '61',
    continent_name: 'AN',
    capital: '',
    currency: 'AUD',
    languages: ['en'],
    emoji: '🇭🇲',
    emojiU: 'U+1F1ED U+1F1F2',
    code3l: 'HMD',
    code2l: 'HM',
  },
  {
    country_name: 'British Indian Ocean Territory',
    native: 'British Indian Ocean Territory',
    phone: '246',
    continent_name: 'AS',
    capital: 'Diego Garcia',
    currency: 'USD',
    languages: ['en'],
    emoji: '🇮🇴',
    emojiU: 'U+1F1EE U+1F1F4',
    code3l: 'IOT',
    code2l: 'IO',
  },
  {
    country_name: 'North Korea',
    native: '북한',
    phone: '850',
    continent_name: 'AS',
    capital: 'Pyongyang',
    currency: 'KPW',
    languages: ['ko'],
    emoji: '🇰🇵',
    emojiU: 'U+1F1F0 U+1F1F5',
    code3l: 'PRK',
    code2l: 'KP',
  },
  {
    country_name: 'South Korea',
    native: '대한민국',
    phone: '82',
    continent_name: 'AS',
    capital: 'Seoul',
    currency: 'KRW',
    languages: ['ko'],
    emoji: '🇰🇷',
    emojiU: 'U+1F1F0 U+1F1F7',
    code3l: 'KOR',
    code2l: 'KR',
  },
  {
    country_name: 'Laos',
    native: 'ສປປລາວ',
    phone: '856',
    continent_name: 'AS',
    capital: 'Vientiane',
    currency: 'LAK',
    languages: ['lo'],
    emoji: '🇱🇦',
    emojiU: 'U+1F1F1 U+1F1E6',
    code3l: 'LAO',
    code2l: 'LA',
  },
  {
    country_name: 'Myanmar [Burma]',
    native: 'မြန်မာ',
    phone: '95',
    continent_name: 'AS',
    capital: 'Naypyidaw',
    currency: 'MMK',
    languages: ['my'],
    emoji: '🇲🇲',
    emojiU: 'U+1F1F2 U+1F1F2',
    code3l: 'MMR',
    code2l: 'MM',
  },
  {
    country_name: 'Nigeria',
    native: 'Nigeria',
    phone: '234',
    continent_name: 'AF',
    capital: 'Abuja',
    currency: 'NGN',
    languages: ['en'],
    emoji: '🇳🇬',
    emojiU: 'U+1F1F3 U+1F1EC',
    code3l: 'NGA',
    code2l: 'NG',
  },
  {
    country_name: 'Papua New Guinea',
    native: 'Papua Niugini',
    phone: '675',
    continent_name: 'OC',
    capital: 'Port Moresby',
    currency: 'PGK',
    languages: ['en'],
    emoji: '🇵🇬',
    emojiU: 'U+1F1F5 U+1F1EC',
    code3l: 'PNG',
    code2l: 'PG',
  },
  {
    country_name: 'Palestine',
    native: 'فلسطين',
    phone: '970',
    continent_name: 'AS',
    capital: 'Ramallah',
    currency: 'ILS',
    languages: ['ar'],
    emoji: '🇵🇸',
    emojiU: 'U+1F1F5 U+1F1F8',
    code2l: 'PS',
    code3l: 'PSE',
  },
  {
    country_name: 'Suricountry_name',
    native: 'Suricountry_name',
    phone: '597',
    continent_name: 'SA',
    capital: 'Paramaribo',
    currency: 'SRD',
    languages: ['nl'],
    emoji: '🇸🇷',
    emojiU: 'U+1F1F8 U+1F1F7',
    code3l: 'SUR',
    code2l: 'SR',
  },
  {
    country_name: 'South Sudan',
    native: 'South Sudan',
    phone: '211',
    continent_name: 'AF',
    capital: 'Juba',
    currency: 'SSP',
    languages: ['en'],
    emoji: '🇸🇸',
    emojiU: 'U+1F1F8 U+1F1F8',
    code3l: 'SSD',
    code2l: 'SS',
  },
  {
    country_name: 'São Tomé and Príncipe',
    native: 'São Tomé e Príncipe',
    phone: '239',
    continent_name: 'AF',
    capital: 'São Tomé',
    currency: 'STN',
    languages: ['pt'],
    emoji: '🇸🇹',
    emojiU: 'U+1F1F8 U+1F1F9',
    code3l: 'STP',
    code2l: 'ST',
  },
  {
    country_name: 'Swaziland',
    native: 'Swaziland',
    phone: '268',
    continent_name: 'AF',
    capital: 'Lobamba',
    currency: 'SZL',
    languages: ['en', 'ss'],
    emoji: '🇸🇿',
    emojiU: 'U+1F1F8 U+1F1FF',
    code3l: 'SWZ',
    code2l: 'SZ',
  },
  {
    country_name: 'French Southern Territories',
    native: 'Territoire des Terres australes et antarctiques fr',
    phone: '262',
    continent_name: 'AN',
    capital: 'Port-aux-Français',
    currency: 'EUR',
    languages: ['fr'],
    emoji: '🇹🇫',
    emojiU: 'U+1F1F9 U+1F1EB',
    code3l: 'ATF',
    code2l: 'TF',
  },
  {
    country_name: 'British Virgin Islands',
    native: 'British Virgin Islands',
    phone: '1',
    continent_name: 'NA',
    capital: 'Road Town',
    currency: 'USD',
    languages: ['en'],
    emoji: '🇻🇬',
    emojiU: 'U+1F1FB U+1F1EC',
    code3l: 'VGB',
    code2l: 'VG',
  },
  {
    country_name: 'U.S. Virgin Islands',
    native: 'United States Virgin Islands',
    phone: '1',
    continent_name: 'NA',
    capital: 'Charlotte Amalie',
    currency: 'USD',
    languages: ['en'],
    emoji: '🇻🇮',
    emojiU: 'U+1F1FB U+1F1EE',
    code3l: 'VIR',
    code2l: 'VI',
  },
  {
    country_name: 'Vietnam',
    native: 'Việt Nam',
    phone: '84',
    continent_name: 'AS',
    capital: 'Hanoi',
    currency: 'VND',
    languages: ['vi'],
    emoji: '🇻🇳',
    emojiU: 'U+1F1FB U+1F1F3',
    code3l: 'VNM',
    code2l: 'VN',
  },
  {
    country_name: 'Kosovo',
    native: 'Republika e Kosovës',
    phone: '383',
    continent_name: 'EU',
    capital: 'Pristina',
    currency: 'EUR',
    languages: ['sq', 'sr'],
    emoji: '🇽🇰',
    emojiU: 'U+1F1FD U+1F1F0',
    code2l: 'XK',
    code3l: 'KOS',
  },
  {
    country_name: 'Vatican City',
    native: 'Vaticano',
    phone: '379',
    continent_name: 'EU',
    capital: 'Vatican City',
    currency: 'EUR',
    languages: ['it', 'la'],
    emoji: '🇻🇦',
    emojiU: 'U+1F1FB U+1F1E6',
    code3l: 'VAT',
    code2l: 'VA',
  },
  {
    country_name: 'Åland',
    native: 'Åland',
    phone: '358',
    continent_name: 'EU',
    capital: 'Mariehamn',
    currency: 'EUR',
    languages: ['sv'],
    emoji: '🇦🇽',
    emojiU: 'U+1F1E6 U+1F1FD',
    code3l: 'ALA',
    code2l: 'AX',
  },
  {
    country_name: 'Brunei',
    native: 'Negara Brunei Darussalam',
    phone: '673',
    continent_name: 'AS',
    capital: 'Bandar Seri Begawan',
    currency: 'BND',
    languages: ['ms'],
    emoji: '🇧🇳',
    emojiU: 'U+1F1E7 U+1F1F3',
    code3l: 'BRN',
    code2l: 'BN',
  },
  {
    country_name: 'Bolivia',
    native: 'Bolivia',
    phone: '591',
    continent_name: 'SA',
    capital: 'Sucre',
    currency: 'BOB,BOV',
    languages: ['es', 'ay', 'qu'],
    emoji: '🇧🇴',
    emojiU: 'U+1F1E7 U+1F1F4',
    code3l: 'BOL',
    code2l: 'BO',
  },
  {
    country_name: 'Bonaire',
    native: 'Bonaire',
    phone: '599',
    continent_name: 'NA',
    capital: 'Kralendijk',
    currency: 'USD',
    languages: ['nl'],
    emoji: '🇧🇶',
    emojiU: 'U+1F1E7 U+1F1F6',
    code3l: 'BES',
    code2l: 'BQ',
  },
  {
    country_name: 'Falkland Islands',
    native: 'Falkland Islands',
    phone: '500',
    continent_name: 'SA',
    capital: 'Stanley',
    currency: 'FKP',
    languages: ['en'],
    emoji: '🇫🇰',
    emojiU: 'U+1F1EB U+1F1F0',
    code3l: 'FLK',
    code2l: 'FK',
  },
  {
    country_name: 'Micronesia',
    native: 'Micronesia',
    phone: '691',
    continent_name: 'OC',
    capital: 'Palikir',
    currency: 'USD',
    languages: ['en'],
    emoji: '🇫🇲',
    emojiU: 'U+1F1EB U+1F1F2',
    code3l: 'FSM',
    code2l: 'FM',
  },
  {
    country_name: 'Faroe Islands',
    native: 'Føroyar',
    phone: '298',
    continent_name: 'EU',
    capital: 'Tórshavn',
    currency: 'DKK',
    languages: ['fo'],
    emoji: '🇫🇴',
    emojiU: 'U+1F1EB U+1F1F4',
    code3l: 'FRO',
    code2l: 'FO',
  },
  {
    country_name: 'Iran',
    native: 'ایران',
    phone: '98',
    continent_name: 'AS',
    capital: 'Tehran',
    currency: 'IRR',
    languages: ['fa'],
    emoji: '🇮🇷',
    emojiU: 'U+1F1EE U+1F1F7',
    code3l: 'IR',
    code2l: 'IR',
  },
  {
    country_name: 'Moldova',
    native: 'Moldova',
    phone: '373',
    continent_name: 'EU',
    capital: 'Chișinău',
    currency: 'MDL',
    languages: ['ro'],
    emoji: '🇲🇩',
    emojiU: 'U+1F1F2 U+1F1E9',
    code3l: 'IRN',
    code2l: 'IR',
  },
  {
    country_name: 'Russia',
    native: 'Россия',
    phone: '7',
    continent_name: 'EU',
    capital: 'Moscow',
    currency: 'RUB',
    languages: ['ru'],
    emoji: '🇷🇺',
    emojiU: 'U+1F1F7 U+1F1FA',
    code3l: 'RUS',
    code2l: 'RU',
  },
  {
    country_name: 'Saint Helena',
    native: 'Saint Helena',
    phone: '290',
    continent_name: 'AF',
    capital: 'Jamestown',
    currency: 'SHP',
    languages: ['en'],
    emoji: '🇸🇭',
    emojiU: 'U+1F1F8 U+1F1ED',
    code3l: 'SHN',
    code2l: 'SH',
  },
  {
    country_name: 'Syria',
    native: 'سوريا',
    phone: '963',
    continent_name: 'AS',
    capital: 'Damascus',
    currency: 'SYP',
    languages: ['ar'],
    emoji: '🇸🇾',
    emojiU: 'U+1F1F8 U+1F1FE',
    code3l: 'SYR',
    code2l: 'SY',
  },
  {
    country_name: 'Tokelau',
    native: 'Tokelau',
    phone: '690',
    continent_name: 'OC',
    capital: 'Fakaofo',
    currency: 'NZD',
    languages: ['en'],
    emoji: '🇹🇰',
    emojiU: 'U+1F1F9 U+1F1F0',
    code3l: 'TKL',
    code2l: 'TK',
  },
  {
    country_name: 'Tanzania',
    native: 'Tanzania',
    phone: '255',
    continent_name: 'AF',
    capital: 'Dodoma',
    currency: 'TZS',
    languages: ['sw', 'en'],
    emoji: '🇹🇿',
    emojiU: 'U+1F1F9 U+1F1FF',
    code3l: 'TZA',
    code2l: 'TZ',
  },
  {
    country_name: 'United States',
    native: 'United States',
    phone: '1',
    continent_name: 'NA',
    capital: 'Washington D.C.',
    currency: 'USD,USN,USS',
    languages: ['en'],
    emoji: '🇺🇸',
    emojiU: 'U+1F1FA U+1F1F8',
    code3l: 'USA',
    code2l: 'US',
  },
  {
    country_name: 'Venezuela',
    native: 'Venezuela',
    phone: '58',
    continent_name: 'SA',
    capital: 'Caracas',
    currency: 'VES',
    languages: ['es'],
    emoji: '🇻🇪',
    emojiU: 'U+1F1FB U+1F1EA',
    code3l: 'VEN',
    code2l: 'VE',
  },
];
