/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface FwButton {
    /**
    * The theme of the button, Values are : `primary`, `secondary`, `danger`
    */
    'color': 'primary' | 'secondary' | 'danger';
    /**
    * Sets the button as disabled when set to true.
    */
    'disabled': boolean;
    /**
    * Sets the button size to block when set to true.
    */
    'expand': boolean;
    /**
    * The size of the button, Values are : `normal`, `mini`
    */
    'size': 'normal' | 'mini';
    /**
    * The native button type: values: `button`, `reset`, `submit`
    */
    'type': 'button' | 'reset' | 'submit';
  }
  interface FwCheckbox {
    /**
    * Property to maintain checked state
    */
    'checked': boolean;
    /**
    * Disables the checkbox
    */
    'disabled': boolean;
    /**
    * Label for checkbox
    */
    'label': string;
    /**
    * Value of the checkbox for within a <form>
    */
    'value': string;
  }
  interface FwLabel {
    /**
    * The type of the label
    */
    'type': string;
    /**
    * The text in the label
    */
    'value': string;
  }
  interface FwRadio {
    /**
    * Property to maintain checked state
    */
    'checked': boolean;
    /**
    * Disables the radio button
    */
    'disabled': boolean;
    /**
    * Label for radio button
    */
    'label': string;
    /**
    * Value of the name for within a <form>
    */
    'name': string;
    /**
    * Value of the radio button for within a <form>
    */
    'value': string;
  }
  interface FwRadioGroup {
    /**
    * If `true`, the radios can be deselected.
    */
    'allowEmpty': boolean;
    /**
    * The name of the control, which is submitted with the form data.
    */
    'name': string;
    /**
    * the value of the radio group.
    */
    'value'?: any | null;
  }
  interface FwSpinner {
    /**
    * The size of the spinner - Options ['small' , 'default', 'medium', 'large']
    */
    'size': string;
  }
}

declare global {


  interface HTMLFwButtonElement extends Components.FwButton, HTMLStencilElement {}
  var HTMLFwButtonElement: {
    prototype: HTMLFwButtonElement;
    new (): HTMLFwButtonElement;
  };

  interface HTMLFwCheckboxElement extends Components.FwCheckbox, HTMLStencilElement {}
  var HTMLFwCheckboxElement: {
    prototype: HTMLFwCheckboxElement;
    new (): HTMLFwCheckboxElement;
  };

  interface HTMLFwLabelElement extends Components.FwLabel, HTMLStencilElement {}
  var HTMLFwLabelElement: {
    prototype: HTMLFwLabelElement;
    new (): HTMLFwLabelElement;
  };

  interface HTMLFwRadioElement extends Components.FwRadio, HTMLStencilElement {}
  var HTMLFwRadioElement: {
    prototype: HTMLFwRadioElement;
    new (): HTMLFwRadioElement;
  };

  interface HTMLFwRadioGroupElement extends Components.FwRadioGroup, HTMLStencilElement {}
  var HTMLFwRadioGroupElement: {
    prototype: HTMLFwRadioGroupElement;
    new (): HTMLFwRadioGroupElement;
  };

  interface HTMLFwSpinnerElement extends Components.FwSpinner, HTMLStencilElement {}
  var HTMLFwSpinnerElement: {
    prototype: HTMLFwSpinnerElement;
    new (): HTMLFwSpinnerElement;
  };
  interface HTMLElementTagNameMap {
    'fw-button': HTMLFwButtonElement;
    'fw-checkbox': HTMLFwCheckboxElement;
    'fw-label': HTMLFwLabelElement;
    'fw-radio': HTMLFwRadioElement;
    'fw-radio-group': HTMLFwRadioGroupElement;
    'fw-spinner': HTMLFwSpinnerElement;
  }
}

declare namespace LocalJSX {
  interface FwButton {
    /**
    * The theme of the button, Values are : `primary`, `secondary`, `danger`
    */
    'color'?: 'primary' | 'secondary' | 'danger';
    /**
    * Sets the button as disabled when set to true.
    */
    'disabled'?: boolean;
    /**
    * Sets the button size to block when set to true.
    */
    'expand'?: boolean;
    /**
    * Emitted when the checbox loses focus.
    */
    'onFwBlur'?: (event: CustomEvent<void>) => void;
    /**
    * Emitted when the button is clicked.
    */
    'onFwClick'?: (event: CustomEvent<void>) => void;
    /**
    * Emitted when the checkbox has focus.
    */
    'onFwFocus'?: (event: CustomEvent<void>) => void;
    /**
    * The size of the button, Values are : `normal`, `mini`
    */
    'size'?: 'normal' | 'mini';
    /**
    * The native button type: values: `button`, `reset`, `submit`
    */
    'type'?: 'button' | 'reset' | 'submit';
  }
  interface FwCheckbox {
    /**
    * Property to maintain checked state
    */
    'checked'?: boolean;
    /**
    * Disables the checkbox
    */
    'disabled'?: boolean;
    /**
    * Label for checkbox
    */
    'label'?: string;
    /**
    * Emitted when the checbox loses focus.
    */
    'onFwBlur'?: (event: CustomEvent<void>) => void;
    /**
    * Emitted when the checkbox value has changed.
    */
    'onFwChange'?: (event: CustomEvent<any>) => void;
    /**
    * Emitted when the checkbox has focus.
    */
    'onFwFocus'?: (event: CustomEvent<void>) => void;
    /**
    * Value of the checkbox for within a <form>
    */
    'value'?: string;
  }
  interface FwLabel {
    /**
    * The type of the label
    */
    'type'?: string;
    /**
    * The text in the label
    */
    'value'?: string;
  }
  interface FwRadio {
    /**
    * Property to maintain checked state
    */
    'checked'?: boolean;
    /**
    * Disables the radio button
    */
    'disabled'?: boolean;
    /**
    * Label for radio button
    */
    'label'?: string;
    /**
    * Value of the name for within a <form>
    */
    'name'?: string;
    /**
    * Emitted when the checbox loses focus.
    */
    'onFwBlur'?: (event: CustomEvent<void>) => void;
    /**
    * Emitted when the radio button value has changed.
    */
    'onFwDeselect'?: (event: CustomEvent<any>) => void;
    /**
    * Emitted when the radio button has focus.
    */
    'onFwFocus'?: (event: CustomEvent<void>) => void;
    /**
    * Emitted when the radio button value has changed.
    */
    'onFwSelect'?: (event: CustomEvent<any>) => void;
    /**
    * Value of the radio button for within a <form>
    */
    'value'?: string;
  }
  interface FwRadioGroup {
    /**
    * If `true`, the radios can be deselected.
    */
    'allowEmpty'?: boolean;
    /**
    * The name of the control, which is submitted with the form data.
    */
    'name'?: string;
    /**
    * Emitted when the value has changed.
    */
    'onFwChange'?: (event: CustomEvent<any>) => void;
    /**
    * the value of the radio group.
    */
    'value'?: any | null;
  }
  interface FwSpinner {
    /**
    * The size of the spinner - Options ['small' , 'default', 'medium', 'large']
    */
    'size'?: string;
  }

  interface IntrinsicElements {
    'fw-button': FwButton;
    'fw-checkbox': FwCheckbox;
    'fw-label': FwLabel;
    'fw-radio': FwRadio;
    'fw-radio-group': FwRadioGroup;
    'fw-spinner': FwSpinner;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'fw-button': LocalJSX.FwButton & JSXBase.HTMLAttributes<HTMLFwButtonElement>;
      'fw-checkbox': LocalJSX.FwCheckbox & JSXBase.HTMLAttributes<HTMLFwCheckboxElement>;
      'fw-label': LocalJSX.FwLabel & JSXBase.HTMLAttributes<HTMLFwLabelElement>;
      'fw-radio': LocalJSX.FwRadio & JSXBase.HTMLAttributes<HTMLFwRadioElement>;
      'fw-radio-group': LocalJSX.FwRadioGroup & JSXBase.HTMLAttributes<HTMLFwRadioGroupElement>;
      'fw-spinner': LocalJSX.FwSpinner & JSXBase.HTMLAttributes<HTMLFwSpinnerElement>;
    }
  }
}


