/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface FwInput {
    /**
    * The first name
    */
    'first': string;
    /**
    * The last name
    */
    'last': string;
    /**
    * The middle name
    */
    'middle': string;
  }
  interface FwLabel {
    /**
    * The type of the label
    */
    'type': string;
    /**
    * The text in the label
    */
    'value': string;
  }
}

declare global {


  interface HTMLFwInputElement extends Components.FwInput, HTMLStencilElement {}
  var HTMLFwInputElement: {
    prototype: HTMLFwInputElement;
    new (): HTMLFwInputElement;
  };

  interface HTMLFwLabelElement extends Components.FwLabel, HTMLStencilElement {}
  var HTMLFwLabelElement: {
    prototype: HTMLFwLabelElement;
    new (): HTMLFwLabelElement;
  };
  interface HTMLElementTagNameMap {
    'fw-input': HTMLFwInputElement;
    'fw-label': HTMLFwLabelElement;
  }
}

declare namespace LocalJSX {
  interface FwInput extends JSXBase.HTMLAttributes<HTMLFwInputElement> {
    /**
    * The first name
    */
    'first'?: string;
    /**
    * The last name
    */
    'last'?: string;
    /**
    * The middle name
    */
    'middle'?: string;
  }
  interface FwLabel extends JSXBase.HTMLAttributes<HTMLFwLabelElement> {
    /**
    * The type of the label
    */
    'type'?: string;
    /**
    * The text in the label
    */
    'value'?: string;
  }

  interface IntrinsicElements {
    'fw-input': FwInput;
    'fw-label': FwLabel;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}


