name: Check Build

on:
  pull_request:
    branches: [ master, next ]
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
  
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'

    # Installs the dependencies
    - name: Install Dependencies
      run: npm ci

    # Runs lints
    - name: Run Linter
      run: npm run code-sanity
    
    # Runs tests
    - name: Runs tests
      run: npm run test
    
    # Builds components
    - name: Builds Components
      run: npm run build:components
